-- GeoStats v14.3 combined Supabase installer
-- Includes the complete v14.2 source-integrity schema plus v14.3 semantic board-quality rules.

-- GeoStats v14.2 combined Supabase installer
-- Safe for users who skipped v14.1: applies the v14.1 analytics/generation-health
-- foundation first, followed by the v14.2 source-integrity system.

-- ============================================================================
-- PART 1: v14.1 analytics and Daily generation health
-- ============================================================================

-- GeoStats v14.1
-- Privacy-conscious first-party analytics and Daily generation health.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  session_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  path text,
  difficulty text,
  challenge_date date,
  value numeric,
  metadata jsonb not null default '{}'::jsonb,
  constraint analytics_events_name_check check (event_name in (
    'page_view','game_started','game_completed','share_clicked',
    'source_opened','account_username_saved','account_signin_requested'
  )),
  constraint analytics_events_difficulty_check check (difficulty is null or difficulty in ('easy','normal','expert')),
  constraint analytics_events_session_check check (length(session_id) between 8 and 80),
  constraint analytics_events_path_check check (path is null or length(path) <= 240)
);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name,created_at desc);
create index if not exists analytics_events_session_created_idx on public.analytics_events(session_id,created_at desc);
create index if not exists analytics_events_user_created_idx on public.analytics_events(user_id,created_at desc) where user_id is not null;

alter table public.analytics_events enable row level security;
-- No public policies: events are accepted only through the validated server route.

create table if not exists public.daily_generation_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  challenge_date date not null,
  status text not null check (status in ('completed','failed','repaired')),
  source text not null default 'admin',
  diagnostics jsonb,
  scores jsonb,
  error_message text
);
create index if not exists daily_generation_runs_date_idx on public.daily_generation_runs(challenge_date desc,created_at desc);
alter table public.daily_generation_runs enable row level security;

create or replace view public.analytics_overview_30d
with (security_invoker=true)
as
select
  count(distinct session_id) filter (where event_name='page_view')::bigint as visitors,
  count(*) filter (where event_name='page_view')::bigint as page_views,
  count(*) filter (where event_name='game_started')::bigint as games_started,
  count(*) filter (where event_name='game_completed')::bigint as games_completed,
  count(*) filter (where event_name='share_clicked')::bigint as shares,
  round(avg(value) filter (where event_name='game_completed'),1) as average_score,
  count(distinct user_id) filter (where user_id is not null)::bigint as signed_in_users_seen
from public.analytics_events
where created_at >= now()-interval '30 days';

create or replace view public.analytics_daily_30d
with (security_invoker=true)
as
select
  created_at::date as activity_date,
  event_name,
  difficulty,
  count(*)::bigint as events,
  count(distinct session_id)::bigint as sessions,
  count(distinct user_id) filter (where user_id is not null)::bigint as signed_in_users,
  round(avg(value),1) as average_value
from public.analytics_events
where created_at >= now()-interval '30 days'
group by created_at::date,event_name,difficulty;

grant all on table public.analytics_events to service_role;
grant all on table public.daily_generation_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

grant select on public.analytics_overview_30d to service_role;
grant select on public.analytics_daily_30d to service_role;

commit;

-- ============================================================================
-- PART 2: v14.2 source integrity validation
-- ============================================================================

-- GeoStats v14.2
-- End-to-end source integrity validation. Imports and editorial approval are not
-- enough: a category becomes playable only after its official-source snapshot,
-- stored values, rankings, unit, year, and series identity agree.

begin;

alter table public.stat_categories
  add column if not exists validation_status text not null default 'pending',
  add column if not exists validation_version text,
  add column if not exists validated_at timestamptz,
  add column if not exists validation_reason text,
  add column if not exists source_snapshot_checksum text,
  add column if not exists stored_snapshot_checksum text,
  add column if not exists validated_observation_count integer,
  add column if not exists validation_expected_count integer,
  add column if not exists validation_mismatch_count integer not null default 0,
  add column if not exists validation_ranking_mismatch_count integer not null default 0;

alter table public.stat_categories drop constraint if exists stat_categories_validation_status_check;
alter table public.stat_categories add constraint stat_categories_validation_status_check
  check (validation_status in ('pending','verified','failed','unable_to_verify'));
alter table public.stat_categories drop constraint if exists stat_categories_validation_counts_check;
alter table public.stat_categories add constraint stat_categories_validation_counts_check
  check (
    (validated_observation_count is null or validated_observation_count >= 0)
    and (validation_expected_count is null or validation_expected_count >= 0)
    and validation_mismatch_count >= 0
    and validation_ranking_mismatch_count >= 0
  );

create index if not exists stat_categories_validation_idx
  on public.stat_categories(validation_status,source_organization,validated_at desc);

create table if not exists public.stat_validation_runs (
  id bigint generated by default as identity primary key,
  source_organization text,
  status text not null check (status in ('running','completed','partial','failed')),
  validation_version text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  categories_selected integer not null default 0,
  categories_verified integer not null default 0,
  categories_failed integer not null default 0,
  categories_unable integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb
);
create index if not exists stat_validation_runs_started_idx on public.stat_validation_runs(started_at desc);

create table if not exists public.stat_category_validation_results (
  id bigint generated by default as identity primary key,
  validation_run_id bigint references public.stat_validation_runs(id) on delete set null,
  category_id text not null references public.stat_categories(id) on delete cascade,
  source_organization text not null,
  validation_status text not null check (validation_status in ('verified','failed','unable_to_verify')),
  validation_version text not null,
  validated_at timestamptz not null default now(),
  common_year smallint,
  expected_observation_count integer,
  stored_observation_count integer,
  compared_observation_count integer,
  value_mismatch_count integer not null default 0,
  ranking_mismatch_count integer not null default 0,
  source_snapshot_checksum text,
  stored_snapshot_checksum text,
  metadata_checks jsonb not null default '{}'::jsonb,
  failure_reason text,
  details jsonb not null default '{}'::jsonb
);
create index if not exists stat_category_validation_results_category_idx
  on public.stat_category_validation_results(category_id,validated_at desc);
create index if not exists stat_category_validation_results_status_idx
  on public.stat_category_validation_results(validation_status,validated_at desc);

create table if not exists public.geostats_feature_flags (
  id text primary key,
  enabled boolean not null default false,
  updated_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);
insert into public.geostats_feature_flags(id,enabled,details)
values ('source_integrity_enforced',false,jsonb_build_object('introducedIn','14.2.0'))
on conflict(id) do nothing;

alter table public.stat_validation_runs enable row level security;
alter table public.stat_category_validation_results enable row level security;
alter table public.geostats_feature_flags enable row level security;
grant all on public.stat_validation_runs to service_role;
grant all on public.stat_category_validation_results to service_role;
grant all on public.geostats_feature_flags to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.source_integrity_is_enforced()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce((select enabled from public.geostats_feature_flags where id='source_integrity_enforced'),false)
$$;

create or replace function public.record_category_validation(
  p_category_id text,
  p_status text,
  p_validation_version text,
  p_common_year integer,
  p_expected_count integer,
  p_stored_count integer,
  p_compared_count integer,
  p_value_mismatch_count integer,
  p_ranking_mismatch_count integer,
  p_source_checksum text,
  p_stored_checksum text,
  p_metadata_checks jsonb,
  p_failure_reason text,
  p_details jsonb,
  p_validation_run_id bigint default null
)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  source_name text;
  group_name text;
begin
  if p_status not in ('verified','failed','unable_to_verify') then
    raise exception 'Invalid validation status %',p_status;
  end if;
  select source_organization,concept_group into source_name,group_name
  from public.stat_categories where id=p_category_id;
  if not found then raise exception 'Unknown stat category %',p_category_id; end if;

  insert into public.stat_category_validation_results(
    validation_run_id,category_id,source_organization,validation_status,validation_version,
    common_year,expected_observation_count,stored_observation_count,compared_observation_count,
    value_mismatch_count,ranking_mismatch_count,source_snapshot_checksum,stored_snapshot_checksum,
    metadata_checks,failure_reason,details
  ) values (
    p_validation_run_id,p_category_id,source_name,p_status,p_validation_version,
    p_common_year,p_expected_count,p_stored_count,p_compared_count,
    greatest(coalesce(p_value_mismatch_count,0),0),greatest(coalesce(p_ranking_mismatch_count,0),0),
    p_source_checksum,p_stored_checksum,coalesce(p_metadata_checks,'{}'::jsonb),p_failure_reason,coalesce(p_details,'{}'::jsonb)
  );

  update public.stat_categories set
    validation_status=p_status,
    validation_version=p_validation_version,
    validated_at=now(),
    validation_reason=case when p_status='verified' then 'Official-source values, metadata, coverage, and rankings matched the stored common-year snapshot.' else coalesce(p_failure_reason,'Source integrity validation did not pass.') end,
    source_snapshot_checksum=p_source_checksum,
    stored_snapshot_checksum=p_stored_checksum,
    validated_observation_count=p_compared_count,
    validation_expected_count=p_expected_count,
    validation_mismatch_count=greatest(coalesce(p_value_mismatch_count,0),0),
    validation_ranking_mismatch_count=greatest(coalesce(p_ranking_mismatch_count,0),0),
    enabled=case when p_status='verified' then enabled else false end,
    eligible_daily=case when p_status='verified' then eligible_daily else false end,
    auto_decision_reason=case
      when p_status='verified' then auto_decision_reason
      else 'Source integrity quarantine: '||coalesce(p_failure_reason,'validation did not pass')
    end,
    metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object(
      'sourceIntegrityStatus',p_status,
      'sourceIntegrityVersion',p_validation_version,
      'sourceSnapshotChecksum',p_source_checksum,
      'storedSnapshotChecksum',p_stored_checksum,
      'sourceIntegrityValidatedAt',now(),
      'sourceIntegrityDetails',coalesce(p_details,'{}'::jsonb)
    ),
    updated_at=now()
  where id=p_category_id;

  perform public.apply_category_governance(p_category_id);
  return p_status;
end;
$$;

-- Duplicate arbitration is source-integrity aware. Failed and unverifiable rows
-- are always excluded. Pending rows remain available only until the one-time
-- full audit is completed and enforcement is explicitly activated.
create or replace function public.refresh_stat_concept_group(p_concept_group text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare chosen text;
declare enforce_integrity boolean:=public.source_integrity_is_enforced();
begin
  if p_concept_group is null or btrim(p_concept_group)='' then return null; end if;

  select category.id into chosen
  from public.stat_categories category
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected'
    and category.auto_qualified=true
    and category.provenance_status='approved'
    and category.independent_validation=true
    and category.curation_status='approved'
    and coalesce(category.credibility_status,'quarantined')<>'quarantined'
    and coalesce(category.credibility_score,0)>=75
    and coalesce(category.objective_status,'uncertain')='objective'
    and coalesce(category.player_quality_status,'blocked')<>'blocked'
    and coalesce(category.verifiability_score,0)>=80
    and coalesce(category.understandability_score,0)>=70
    and coalesce(category.fun_score,0)>=55
    and coalesce(category.validation_status,'pending') not in ('failed','unable_to_verify')
    and (not enforce_integrity or category.validation_status='verified')
  order by
    category.governance_priority asc,
    category.validation_status='verified' desc,
    category.player_quality_status='approved' desc,
    category.verifiability_score desc,
    category.understandability_score desc,
    category.fun_score desc,
    category.credibility_score desc,
    category.quality_score desc,
    category.common_year_coverage desc,
    category.latest_available_year desc nulls last,
    category.id
  limit 1;

  update public.stat_categories category
  set
    enabled=case when category.id=chosen then true else false end,
    eligible_daily=case when category.id=chosen then true else false end,
    review_status=case
      when category.review_status='rejected' then 'rejected'
      when category.validation_status in ('failed','unable_to_verify') then 'candidate'
      when enforce_integrity and category.validation_status<>'verified' then 'needs_review'
      when category.curation_status='excluded' then 'candidate'
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then 'candidate'
      when category.player_quality_status='blocked' then 'candidate'
      when category.id=chosen then 'approved'
      when category.auto_qualified and category.provenance_status='approved' then 'candidate'
      when category.auto_qualified then 'needs_review'
      else 'candidate'
    end,
    duplicate_status=case
      when category.validation_status in ('failed','unable_to_verify')
        or (enforce_integrity and category.validation_status<>'verified')
        or category.curation_status='excluded'
        or category.credibility_status='quarantined'
        or coalesce(category.credibility_score,0)<75
        or category.player_quality_status='blocked' then 'not_eligible'
      when category.id=chosen then 'preferred'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'superseded'
      else 'not_eligible'
    end,
    superseded_by=case when category.id<>chosen and chosen is not null then chosen else null end,
    auto_decision_reason=case
      when category.validation_status in ('failed','unable_to_verify') then 'Source integrity quarantine: '||coalesce(category.validation_reason,'validation did not pass')
      when enforce_integrity and category.validation_status<>'verified' then 'Awaiting official-source integrity validation.'
      when category.curation_status='excluded' then category.curation_reason
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then category.credibility_reason
      when category.player_quality_status='blocked' then category.player_quality_reason
      when category.id=chosen then 'Selected after source integrity, quality, provenance, credibility, objectivity, clarity, fun, and duplicate review.'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'Passed the gates but was superseded by a stronger near-duplicate.'
      else category.auto_decision_reason
    end,
    updated_at=now()
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected';

  return chosen;
end;
$$;

create or replace function public.apply_category_governance(p_category_id text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare group_name text;
begin
  perform public.apply_category_curation(p_category_id);
  perform public.apply_category_credibility(p_category_id);
  perform public.apply_category_player_quality(p_category_id);
  select concept_group into group_name from public.stat_categories where id=p_category_id;
  if group_name is null then
    update public.stat_categories set concept_group=id where id=p_category_id;
    group_name:=p_category_id;
  end if;
  return public.refresh_stat_concept_group(group_name);
end;
$$;

create or replace function public.activate_source_integrity_enforcement()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare pending_enabled integer;
declare verified_count integer;
declare quarantined_count integer;
declare row record;
begin
  select count(*) into pending_enabled from public.stat_categories
  where (enabled or eligible_daily)
    and coalesce(validation_status,'pending')<>'verified';
  if pending_enabled>0 then
    raise exception 'Cannot activate source integrity enforcement: % currently playable categories are not verified.',pending_enabled;
  end if;
  update public.geostats_feature_flags
    set enabled=true,updated_at=now(),details=details||jsonb_build_object('activatedAt',now(),'activatedBy','v14.2 audit')
    where id='source_integrity_enforced';
  for row in select distinct concept_group from public.stat_categories where concept_group is not null loop
    perform public.refresh_stat_concept_group(row.concept_group);
  end loop;
  select count(*) into verified_count from public.stat_categories where validation_status='verified';
  select count(*) into quarantined_count from public.stat_categories where validation_status in ('failed','unable_to_verify');
  return jsonb_build_object('enforced',true,'verified',verified_count,'quarantined',quarantined_count);
end;
$$;

create or replace view public.data_integrity_by_source
with (security_invoker=true)
as
select
  source_organization as source,
  count(*)::bigint as categories,
  count(*) filter(where enabled and eligible_daily)::bigint as playable,
  count(*) filter(where validation_status='verified')::bigint as verified,
  count(*) filter(where validation_status='failed')::bigint as failed,
  count(*) filter(where validation_status='unable_to_verify')::bigint as unable_to_verify,
  count(*) filter(where validation_status='pending')::bigint as pending,
  max(validated_at) as last_validated_at
from public.stat_categories
group by source_organization;

create or replace view public.data_integrity_overview
with (security_invoker=true)
as
select
  public.source_integrity_is_enforced() as enforcement_enabled,
  count(*)::bigint as categories,
  count(*) filter(where enabled and eligible_daily)::bigint as playable,
  count(*) filter(where validation_status='verified')::bigint as verified,
  count(*) filter(where validation_status='failed')::bigint as failed,
  count(*) filter(where validation_status='unable_to_verify')::bigint as unable_to_verify,
  count(*) filter(where validation_status='pending')::bigint as pending,
  count(*) filter(where (enabled or eligible_daily) and validation_status<>'verified')::bigint as unverified_playable
from public.stat_categories;

create or replace view public.data_integrity_issues
with (security_invoker=true)
as
select id,title,source_organization,source_dataset,source_indicator_code,validation_status,
  validation_reason,validated_at,common_year,common_year_coverage,validation_expected_count,
  validated_observation_count,validation_mismatch_count,validation_ranking_mismatch_count
from public.stat_categories
where validation_status in ('failed','unable_to_verify')
order by validated_at desc nulls last,source_organization,title;

grant select on public.data_integrity_by_source to service_role;
grant select on public.data_integrity_overview to service_role;
grant select on public.data_integrity_issues to service_role;
revoke all on function public.record_category_validation(text,text,text,integer,integer,integer,integer,integer,integer,text,text,jsonb,text,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.activate_source_integrity_enforcement() from public,anon,authenticated;
grant execute on function public.record_category_validation(text,text,text,integer,integer,integer,integer,integer,integer,text,text,jsonb,text,jsonb,bigint) to service_role;
grant execute on function public.activate_source_integrity_enforcement() to service_role;
grant execute on function public.source_integrity_is_enforced() to service_role;

commit;

-- GeoStats v14.3
-- Board-quality semantics and globally meaningful winners.
-- Every playable category receives a hard semantic family. Daily boards may use
-- at most one category from each family, and the board winner for every category
-- must rank within the global top 30 among the verified country snapshot.

begin;

alter table public.stat_categories
  add column if not exists semantic_family text,
  add column if not exists semantic_topic text;

with category_text as (
  select
    id,
    lower(concat_ws(' ',id,title,short_title,description,family,source_organization,source_indicator_code,concept_group,
      metadata->>'element',metadata->>'source_indicator_name')) as searchable
  from public.stat_categories
), classified as (
  select
    id,
    case
      when searchable ~ '(refugee|asylum|displacement)' and searchable ~ '(origin|originating|by origin|by-origin)'
        then 'forced-displacement-origin'
      when searchable ~ '(refugee|asylum|displacement)' and searchable ~ '(hosted|received|destination|receiving)'
        then 'forced-displacement-destination'
      when searchable ~ '(refugee|asylum|displacement)'
        then 'forced-displacement'
      when searchable ~ '(employment.to.population|employment-to-population|unemployment|labor.force.participation|labour.force.participation)'
        then 'labor-market-utilization'
      when searchable ~ '(labor.productivity|labour.productivity|productivity.growth)'
        then 'labor-productivity'
      when searchable ~ '(self.employment|wage.employment|employment.status)'
        then 'employment-status'
      when searchable ~ '(^|[^a-z])yield([^a-z]|$)' and searchable ~ '(faostat|qcl)'
        then 'crop-yield'
      when searchable ~ '(^|[^a-z])production([^a-z]|$)' and searchable ~ '(faostat|qcl)'
        then 'crop-production'
      when searchable ~ '(area.harvested|harvested.area)' and searchable ~ '(faostat|qcl)'
        then 'crop-harvested-area'
      when searchable ~ '(gdp|gross.domestic.product|economic.output)'
        then 'economic-output'
      when searchable ~ '(forest.area|forest.cover|forest.percent|forest.share|least.forest)'
        then 'forest-cover'
      when searchable ~ '(urban.population|rural.population|urbanization|settlement.share)'
        then 'settlement-share'
      when searchable ~ 'life.expectancy' then 'life-expectancy'
      when searchable ~ 'infant.mortality' then 'infant-mortality'
      when searchable ~ 'maternal.mortality' then 'maternal-mortality'
      when searchable ~ '(vaccination|immunization|measles.vaccine)' then 'immunization-coverage'
      when searchable ~ '(merchandise.export|general.export|exports.share)' then 'general-exports'
      when searchable ~ '(merchandise.import|general.import)' then 'general-imports'
      else null
    end as inferred_family
  from category_text
)
update public.stat_categories category
set
  semantic_family=coalesce(
    classified.inferred_family,
    nullif(category.metadata->>'semanticFamily',''),
    nullif(category.concept_group,''),
    category.id
  ),
  semantic_topic=coalesce(
    nullif(category.metadata->>'semanticTopic',''),
    nullif(category.concept_group,''),
    category.id
  ),
  metadata=coalesce(category.metadata,'{}'::jsonb)||jsonb_build_object(
    'semanticFamily',coalesce(classified.inferred_family,nullif(category.metadata->>'semanticFamily',''),nullif(category.concept_group,''),category.id),
    'semanticTopic',coalesce(nullif(category.metadata->>'semanticTopic',''),nullif(category.concept_group,''),category.id),
    'semanticRulesVersion','v14.3'
  ),
  updated_at=now()
from classified
where classified.id=category.id;

alter table public.stat_categories alter column semantic_family set not null;
alter table public.stat_categories alter column semantic_topic set not null;

create index if not exists stat_categories_semantic_family_idx
  on public.stat_categories(semantic_family,enabled,eligible_daily);
create index if not exists stat_categories_semantic_topic_idx
  on public.stat_categories(semantic_topic,source_organization);

create or replace view public.board_semantic_conflicts
with (security_invoker=true)
as
select
  first.id as first_category_id,
  first.title as first_title,
  second.id as second_category_id,
  second.title as second_title,
  first.semantic_family,
  first.family as first_domain,
  second.family as second_domain
from public.stat_categories first
join public.stat_categories second
  on first.id < second.id
 and first.semantic_family=second.semantic_family
where first.enabled and first.eligible_daily
  and second.enabled and second.eligible_daily
order by first.semantic_family,first.title,second.title;

create or replace view public.board_quality_category_status
with (security_invoker=true)
as
select
  category.id,
  category.title,
  category.source_organization,
  category.family as broad_domain,
  category.semantic_family,
  category.semantic_topic,
  category.enabled,
  category.eligible_daily,
  category.validation_status,
  category.common_year,
  category.common_year_coverage,
  count(conflict.second_category_id)::bigint as same_family_playable_conflicts
from public.stat_categories category
left join public.board_semantic_conflicts conflict
  on conflict.first_category_id=category.id or conflict.second_category_id=category.id
where category.review_status<>'rejected'
group by category.id,category.title,category.source_organization,category.family,
  category.semantic_family,category.semantic_topic,category.enabled,category.eligible_daily,
  category.validation_status,category.common_year,category.common_year_coverage;

grant select on public.board_semantic_conflicts to service_role;
grant select on public.board_quality_category_status to service_role;

-- v14.3 makes source integrity fail-closed permanently, not only after the
-- feature flag is activated. Imports and failed audits may preserve editorial
-- approval, but a category cannot become enabled until it is verified.
create or replace function public.refresh_stat_concept_group(p_concept_group text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare chosen text;
begin
  if p_concept_group is null or btrim(p_concept_group)='' then return null; end if;

  select category.id into chosen
  from public.stat_categories category
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected'
    and category.auto_qualified=true
    and category.provenance_status='approved'
    and category.independent_validation=true
    and category.curation_status='approved'
    and coalesce(category.credibility_status,'quarantined')<>'quarantined'
    and coalesce(category.credibility_score,0)>=75
    and coalesce(category.objective_status,'uncertain')='objective'
    and coalesce(category.player_quality_status,'blocked')<>'blocked'
    and coalesce(category.verifiability_score,0)>=80
    and coalesce(category.understandability_score,0)>=70
    and coalesce(category.fun_score,0)>=55
    and category.validation_status='verified'
  order by
    category.governance_priority asc,
    category.player_quality_status='approved' desc,
    category.verifiability_score desc,
    category.understandability_score desc,
    category.fun_score desc,
    category.credibility_score desc,
    category.quality_score desc,
    category.common_year_coverage desc,
    category.latest_available_year desc nulls last,
    category.id
  limit 1;

  update public.stat_categories category
  set
    enabled=case when category.id=chosen then true else false end,
    eligible_daily=case when category.id=chosen then true else false end,
    review_status=case
      when category.review_status='rejected' then 'rejected'
      when category.validation_status in ('failed','unable_to_verify') then 'candidate'
      when category.validation_status<>'verified' then 'needs_review'
      when category.curation_status='excluded' then 'candidate'
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then 'candidate'
      when category.player_quality_status='blocked' then 'candidate'
      when category.id=chosen then 'approved'
      when category.auto_qualified and category.provenance_status='approved' then 'candidate'
      when category.auto_qualified then 'needs_review'
      else 'candidate'
    end,
    duplicate_status=case
      when category.validation_status<>'verified'
        or category.curation_status='excluded'
        or category.credibility_status='quarantined'
        or coalesce(category.credibility_score,0)<75
        or category.player_quality_status='blocked' then 'not_eligible'
      when category.id=chosen then 'preferred'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'superseded'
      else 'not_eligible'
    end,
    superseded_by=case when category.id<>chosen and chosen is not null then chosen else null end,
    auto_decision_reason=case
      when category.validation_status in ('failed','unable_to_verify') then 'Source integrity quarantine: '||coalesce(category.validation_reason,'validation did not pass')
      when category.validation_status<>'verified' then 'Awaiting official-source integrity validation.'
      when category.curation_status='excluded' then category.curation_reason
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then category.credibility_reason
      when category.player_quality_status='blocked' then category.player_quality_reason
      when category.id=chosen then 'Selected after source integrity, quality, provenance, credibility, objectivity, clarity, fun, and duplicate review.'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'Passed the gates but was superseded by a stronger near-duplicate.'
      else category.auto_decision_reason
    end,
    updated_at=now()
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected';

  return chosen;
end;
$$;

-- Re-evaluate all existing concept groups under the permanent verified-only gate.
do $$
declare row record;
begin
  for row in select distinct concept_group from public.stat_categories where concept_group is not null loop
    perform public.refresh_stat_concept_group(row.concept_group);
  end loop;
end;
$$;

-- Keep activation fail-closed, but record that the semantic/top-30 release performed it.
create or replace function public.activate_source_integrity_enforcement()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare pending_enabled integer;
declare verified_count integer;
declare quarantined_count integer;
declare row record;
begin
  select count(*) into pending_enabled from public.stat_categories
  where (enabled or eligible_daily)
    and coalesce(validation_status,'pending')<>'verified';
  if pending_enabled>0 then
    raise exception 'Cannot activate source integrity enforcement: % currently playable categories are not verified.',pending_enabled;
  end if;
  update public.geostats_feature_flags
    set enabled=true,updated_at=now(),details=coalesce(details,'{}'::jsonb)||jsonb_build_object(
      'activatedAt',now(),
      'activatedBy','v14.3 source-integrity and semantic-quality audit',
      'boardWinnerGlobalRankLimit',30,
      'semanticFamilyUniqueness',true
    )
    where id='source_integrity_enforced';
  for row in select distinct concept_group from public.stat_categories where concept_group is not null loop
    perform public.refresh_stat_concept_group(row.concept_group);
  end loop;
  select count(*) into verified_count from public.stat_categories where validation_status='verified';
  select count(*) into quarantined_count from public.stat_categories where validation_status in ('failed','unable_to_verify');
  return jsonb_build_object(
    'enforced',true,
    'verified',verified_count,
    'quarantined',quarantined_count,
    'boardWinnerGlobalRankLimit',30,
    'semanticFamilyUniqueness',true
  );
end;
$$;

commit;
