"use client";
import { useMemo, useState } from "react";
import type { AnimalDataset, BoardCandidate, Trait } from "../lib/animalstats";
import { AnimalSourcePanel } from "./AnimalResults";
import { formatAnimalValue } from "../lib/animalstatsFormatting";

export default function AnimalDataBrowser({ data, boards, initialTab, onPlay }: { data: AnimalDataset; boards: BoardCandidate[]; initialTab: "categories" | "animals"; onPlay: (id: string) => void }) {
  const [tab, setTab] = useState(initialTab);
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState("all");
  const [sourceTrait, setSourceTrait] = useState<Trait | null>(null);
  const used = useMemo(() => new Set(boards.flatMap(b => b.traitIds)), [boards]);
  const traits = useMemo(() => data.traits.filter(t => t.oneSided ? used.has(t.id) : t.direction === "higher_wins" && (used.has(t.id) || used.has(t.counterTraitId ?? ""))).sort((a, b) => a.displayName.localeCompare(b.displayName)), [data.traits, used]);
  const observations = useMemo(() => new Map(traits.map(t => [t.id, data.values.filter(v => v.traitId === t.id && v.confidence === "approved" && v.observationType !== "imputed")])), [traits, data.values]);
  const prizeNames = useMemo(() => new Set(data.traits.filter(t => used.has(t.id)).map(t => t.displayName)).size, [data.traits, used]);
  const allTraits = useMemo(() => new Map(data.traits.map(t => [t.id, t])), [data.traits]);
  const sources = useMemo(() => new Map(data.sources.map(s => [s.id, s])), [data.sources]);
  return <section className="panel animalDataBrowser"><h2>Data &amp; methodology</h2><nav className="personalModeTabs" aria-label="Animal data"><button onClick={() => { setTab("categories"); setQuery(""); }} className={tab === "categories" ? "active" : ""}>Categories</button><button onClick={() => { setTab("animals"); setQuery(""); }} className={tab === "animals" ? "active" : ""}>Animals</button></nav><div className="animalDataFilters"><label>{tab === "categories" ? "Find a category" : "Find an animal"}<input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={tab === "categories" ? "Weight, teeth, height…" : "Bear, shark, fox…"}/></label>{tab === "categories" && <label>Categories<select value={kind} onChange={event => setKind(event.target.value)}><option value="all">All</option><option value="intuitive">Intuitive</option><option value="specialist">Specialist</option></select></label>}</div>
  {tab === "categories" ? <><p className="animalCoverageNote">{prizeNames} prize names. Opposites use the same observations.</p><div className="animalDataTable"><table><thead><tr><th>Category</th><th>Coverage</th><th>Source</th><th>Explore</th></tr></thead><tbody>{traits.filter(t => (kind === "all" || t.categoryKind === kind) && `${t.displayName} ${allTraits.get(t.counterTraitId!)?.displayName} ${t.metricKey}`.toLowerCase().includes(query.toLowerCase())).map(t => <tr key={t.id}><td><strong>{t.displayName}</strong><small>{allTraits.get(t.counterTraitId!)?.displayName}</small><details><summary>Definition</summary><p>{t.definition}</p></details></td><td>{observations.get(t.id)?.length} animals</td><td><a href={sources.get(t.canonicalSourceId)?.url} target="_blank" rel="noreferrer">{sources.get(t.canonicalSourceId)?.name}</a><small>{sources.get(t.canonicalSourceId)?.versionYear}</small></td><td><button onClick={() => setSourceTrait(t)}>Data &amp; Source</button><div className="animalDataPlayButtons">{used.has(t.id) && <button onClick={() => onPlay(t.id)}>Play</button>}{t.counterTraitId && used.has(t.counterTraitId) && <button onClick={() => onPlay(t.counterTraitId!)}>Play opposite</button>}</div></td></tr>)}</tbody></table></div></> : <><p className="animalCoverageNote">{data.animals.length} animals and breeds. Data coverage varies by category.</p><div className="animalDataTable"><table><thead><tr><th>Animal</th><th>Group</th><th>Measurements</th></tr></thead><tbody>{data.animals.filter(a => `${a.commonName} ${a.scientificName} ${a.taxonomicGroup}`.toLowerCase().includes(query.toLowerCase())).map(a => { const values = traits.flatMap(t => (observations.get(t.id) ?? []).filter(v => v.animalId === a.id).map(v => ({ t, v }))); return <tr key={a.id}><td><strong>{a.commonName}</strong><small>{a.entityType === "breed" ? `${a.scientificName} · breed` : a.scientificName}</small></td><td>{a.taxonomicGroup.replaceAll("-", " ")}</td><td><details><summary>{values.length} sourced values</summary>{values.map(({t,v}) => <p key={t.id}><button onClick={() => setSourceTrait(t)}>{t.displayName}</button> · {formatAnimalValue(v.valueNumeric, v.unit)}</p>)}</details></td></tr>; })}</tbody></table></div></>}
  {sourceTrait && <AnimalSourcePanel data={data} trait={sourceTrait} boardIds={[]} onClose={() => setSourceTrait(null)} />}
  </section>;
}
