"""Distinct new concepts and primary evidence leads; pairs remain adjacent."""
import csv,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1];R=ROOT/'data/animalstats/research'
# id | bucket | high | low | interest | source | evidence | gate
SPEC='''heart-rate|Routines|Fastest resting heartbeat|Slowest resting heartbeat|intuitive|https://github.com/stacyderuiter/mammal-allometry|acquired|Beats/min; adult, awake, resting and unsedated flags required. Do not use predicted equations.
breathing-rate|Routines|Fastest resting breathing|Slowest resting breathing|intuitive|https://github.com/stacyderuiter/mammal-allometry|acquired|Breaths/min; inactive awake adults, at surface or ashore for aquatic mammals; no breath-hold substitution.
breath-volume|Anatomy|Largest breath|Smallest breath|intuitive|https://github.com/stacyderuiter/mammal-allometry|acquired|Measured tidal volume in mL per breath; not lung capacity. Conditions and explicit units required.
heart-stroke-volume|Anatomy|Most blood pumped per heartbeat|Least blood pumped per heartbeat|specialist|https://github.com/stacyderuiter/mammal-allometry|acquired|Direct measured stroke volume only. Exclude model-derived cardiac output and calculated values lacking actual observations.
field-energy|Feeding|Most daily energy burned in the wild|Least daily energy burned in the wild|intuitive|https://zenodo.org/records/16894769|acquired|Study-reported field energy expenditure; common time/energy units, comparable age and activity. Reject predictions and imputation.
resting-energy|Routines|Most energy burned at rest|Least energy burned at rest|specialist|https://github.com/stacyderuiter/mammal-allometry|acquired|Basal versus resting metabolic rate separate; strict condition flags and unit conversion only. No allometric estimates.
chewing-rate|Feeding|Fastest chewer|Slowest chewer|intuitive|https://doi.org/10.1644/07-MAMM-A-188.1|paper_table_lead|132-species table located; cycle duration measured/compiled, food type and chewing versus incising separate. No predicted rates.
food-retention|Feeding|Longest food passage time|Shortest food passage time|intuitive|https://pubmed.ncbi.nlm.nih.gov/39653272/|paper_lead|149 mammal and 33 bird species reported. Match marker, food and particle versus fluid; not a generic digestion time.
intestine-length|Anatomy|Longest intestines|Shortest intestines|intuitive|https://doi.org/10.5061/dryad.z8w9ghxb8|dataset_lead|Whole intestinal length only, same preservation and stretching methods. Do not split each gut section into more prizes.
milk-fat|Parenting|Fattiest milk|Least fatty milk|intuitive|https://doi.org/10.1111/1365-2656.12095|paper_lead|Measured g fat per 100g milk at comparable lactation stage. Corrected 2019 table has model imputations; exclude those cells.
milk-protein|Parenting|Most protein-rich milk|Least protein-rich milk|intuitive|https://doi.org/10.1111/1365-2656.12095|paper_lead|Measured protein g/100g milk, same lactation stage and assay basis. Not grams per day.
milk-sugar|Parenting|Most sugar-rich milk|Least sugar-rich milk|intuitive|https://doi.org/10.7717/peerj.8085|paper_lead|Total measured sugar; not lactose alone. Fifteen imputed sugar cells in later analyses must be excluded.
milk-energy|Parenting|Most energy-rich milk|Least energy-rich milk|intuitive|https://doi.org/10.1111/1365-2656.12095|paper_lead|Energy per gram; require measured calorimetry or explicit source basis. No energy computed by us from guessed composition.
wingbeat-frequency|Movement|Fastest wingbeats|Slowest wingbeats|intuitive|https://doi.org/10.1242/jeb.199.7.1613;https://doi.org/10.1242/jeb.060855|paper_lead|Measured cruising/hovering protocols separated. Birds and bats offer independent coverage; predictions excluded.
shake-frequency|Routines|Fastest shake to dry off|Slowest shake to dry off|intuitive|https://pmc.ncbi.nlm.nih.gov/articles/PMC3481573/|paper_table_lead|Measured wet-mammal oscillations per second, not predicted mass scaling or tremor frequency. Small samples must remain explicit.
whisker-length|Anatomy|Longest whiskers|Shortest whiskers|intuitive|https://zenodo.org/records/4942927|acquired|11-species experiment; whisker length is not whisker span. Preserve whisker identity, intact versus cut and source units.
grip-force|Strength|Strongest climbing grip|Weakest climbing grip|intuitive|https://zenodo.org/records/4951666|acquired|Measured maximum adhesive force in N; source specimen IDs require species key. Surface, pull direction and pad contact matched.
venom-yield|Survival|Most venom produced|Least venom produced|intuitive|https://pmc.ncbi.nlm.nih.gov/articles/PMC12092123/|paper_lead|75-spider compilation; missing S1 from latest repository record. Dry mass versus wet volume kept separate; milking is not venom injected in a bite.
venom-potency|Survival|Most potent venom in a shared test|Least potent venom in a shared test|specialist|https://pmc.ncbi.nlm.nih.gov/articles/PMC12092123/|paper_lead|Compare the same test organism, route and LD50 units. No deadliest-to-human claim; no combining prey-specific assays.
shell-strength|Strength|Hardest shell to crack|Easiest shell to crack|intuitive|https://doi.org/10.31931/FMBC-D-21-00001|paper_lead|Eight-bivalve study; force to fracture versus material stress are distinct. Match loading geometry, size context and shell condition.
shell-thickness|Anatomy|Thickest shell|Thinnest shell|intuitive|https://doi.org/10.31931/FMBC-D-21-00001|paper_lead|Whole animal shell, same location and adult stage; not eggshell or proxy thickness index.
skin-thickness|Anatomy|Thickest skin|Thinnest skin|intuitive|https://doi.org/10.1111/ahe.12967|paper_lead|Total skin thickness, same body region and adult stage. Epidermis alone is not skin; access/embargo must be checked.
visual-field|Senses|Widest field of view|Narrowest field of view|intuitive|https://pubmed.ncbi.nlm.nih.gov/18245624/;https://pmc.ncbi.nlm.nih.gov/articles/PMC12629130/|paper_lead|Measured horizontal cyclopean field at resting eye position, degrees; not binocular overlap or orbit orientation proxy.
visual-temporal-resolution|Senses|Detects the fastest flicker|Detects the slowest flicker|specialist|https://pmc.ncbi.nlm.nih.gov/articles/PMC4798572/|paper_lead|Critical flicker fusion threshold, common light level and behavioral/retinal method separate. No subjective slow-motion vision label.
vocal-repertoire|Sound|Most distinct call types|Fewest distinct call types|intuitive|https://zenodo.org/records/5016383;https://zenodo.org/records/20616324|acquired|Adult repertoire definitions and effort vary. 253-bird and 42-primate source datasets; no counting dialects or recording clips as call types.
prey-mass|Feeding|Largest recorded prey taken||intuitive|https://doi.org/10.1371/journal.pone.0106402|acquired_pdf|108 carnivores; use one common endpoint such as largest documented prey mass reversed. Do not reverse maximum for one prize and minimum for another. Distinguish predation from scavenging.
kill-frequency|Feeding|Most frequent prey kills|Least frequent prey kills|specialist|https://doi.org/10.5061/dryad.n23q7q1|dataset_lead|Measured kills per day under comparable field definitions; group versus individual rates and inferred rates excluded.
low-oxygen-tolerance|Survival|Needs the least oxygen in water|Needs the most oxygen in water|intuitive|https://doi.org/10.14466/CefasDataHub.121|dataset_lead|331 measurements/151 fish reported. Pcrit is a metabolic threshold, not lethal survival; temperature, salinity, respirometry and units must match.
claw-length|Anatomy|Longest claws|Shortest claws|intuitive|https://doi.org/10.1002/jmor.21317|paper_lead|80 claw specimens reported across birds/mammals/reptile; curved outer length versus chord distinguished, same digit and sheath versus bone.
fang-length|Anatomy|Longest fangs|Shortest fangs|intuitive|https://doi.org/10.6078/D17M5J|dataset_lead|Measured exposed fang length, not maxilla length or proxy fang-size score. Rear-fanged snake coverage alone is narrow.
eye-opening-age|Development|Latest eyes open after birth|Earliest eyes open after birth|intuitive|https://doi.org/10.1890/08-1494.1|existing_catalog|PanTHERIA age-at-eye-opening days; original measured records and uncertainty required. Missing -999 excluded; not maturity age.
teat-count|Anatomy|Most nipples|Fewest nipples|intuitive|https://doi.org/10.1890/08-1494.1|existing_catalog|PanTHERIA teat count; counts versus pairs explicit, species exceptions/source verification. No inferred count from litter size.
dispersal-age|Development|Latest leaves its birth group|Earliest leaves its birth group|intuitive|https://doi.org/10.1890/08-1494.1|existing_catalog|Natal dispersal age in days; sex and social context matched. Not weaning, maturity or independence age.
newborn-length|Size|Longest newborn|Shortest newborn|intuitive|https://doi.org/10.1890/08-1494.1|existing_catalog|Neonate head-body length in mm; anatomical endpoints and neonatal timing consistent, exclude estimates.
silk-strength|Strength|Strongest silk|Weakest silk|intuitive|https://academic.oup.com/evolut/article/78/12/2032/7758014|paper_lead|164-spider comparative analysis; measured same silk type/tensile protocol. Tensile strength is not force to break a whole web.
silk-stretch|Strength|Most stretchable silk|Least stretchable silk|intuitive|https://doi.org/10.5061/dryad.7n38s11|dataset_lead|Measured strain at rupture, same silk type and extraction speed; not toughness or modulus.
arm-count|Anatomy|Most arms and tentacles|Fewest arms and tentacles|intuitive|https://ocean.si.edu/ocean-life/invertebrates/octopuses-squids-and-relatives|account_lead|Species-level anatomical count, distinguish arms/tentacles and damaged individuals. Many ties; needs diverse species and board eligibility.
eye-count|Anatomy|Most eyes|Fewest eyes|intuitive|https://doi.org/10.1146/annurev-vision-121820-074736|review_lead|Define functional eyes versus ocelli/photoreceptive patches; species-specific measured counts and ties. No counting compound-eye facets as separate eyes.
reaction-latency|Movement|Fastest escape reaction|Slowest escape reaction|intuitive|https://pubmed.ncbi.nlm.nih.gov/33431597/;https://pmc.ncbi.nlm.nih.gov/articles/PMC11413494/|paper_lead|Time from common stimulus to first visible movement. Not take-off duration; limited fish/rodent studies cannot be pooled blindly.
strike-speed|Movement|Fastest prey-catching strike|Slowest prey-catching strike|intuitive|https://doi.org/10.5061/dryad.gf1vhhn1t|dataset_lead|Comparative soft-tissue capture kinematics; speed endpoint and body part must be comparable. Not whole-animal travel speed.
documented-tool-use|Cognition|Documented tool user||intuitive|https://github.com/datadiversitylab/ACDB|acquired|One-sided factual attribute. Culture records are observation-biased, so absence is not inability. Not a scalar rank; requires separate game eligibility decision.
'''
rows=[]
for line in SPEC.strip().splitlines():
 id,bucket,high,low,interest,url,evidence,gate=line.split('|')
 rows.append({'id':id,'bucket':bucket,'high_label':high,'low_label':low,'interest':interest,'status':'downloaded_source_requires_endpoint_audit' if evidence in ('acquired','acquired_pdf','existing_catalog') else 'evidence_lead','source_ids':'discovery-'+id,'source_urls':url,'coverage':'See source-specific audit; no globally balanced coverage claimed.','evidence_gate':gate,'manual_decision':'awaiting_user_review','game_approved':'False','discovery_evidence':evidence,'recommendation':'keep' if interest=='intuitive' and id!='documented-tool-use' else 'hold','recommendation_reason':'Distinct understandable comparison worth pursuing; source-level eligibility still required.' if interest=='intuitive' else 'Optional specialist comparison; keep out of main boards unless mixed with intuitive prizes.'})
old=list(csv.DictReader((R/'expanded-category-register.csv').open()));assert not ({x['id'] for x in old}&{x['id'] for x in rows});assert len({x['id'] for x in rows})==len(rows)
with (R/'discovery-category-register.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
print(json.dumps({'new_concepts':len(rows),'new_proposed_prize_categories':sum(1+bool(r['low_label']) for r in rows),'intuitive':sum(r['interest']=='intuitive' for r in rows),'specialist':sum(r['interest']=='specialist' for r in rows),'combined_concepts':len(old)+len(rows),'combined_proposed_prize_categories':len(old)*2+sum(1+bool(r['low_label']) for r in rows),'new_playable_approvals':0}))
