#!/usr/bin/env python3
"""Import reproducible mapped-range facts; exclude inferred animal attributes."""
import csv,json,pathlib,hashlib,math,collections,requests
R=pathlib.Path(__file__).resolve().parents[1];P=R/'data/animalstats/source/underrepresented-20261010/TetrapodTraits_v2.0.1.csv'
if not P.exists():
 r=requests.get('https://zenodo.org/api/records/18926700/files/TetrapodTraits_v2.0.1.csv/content',timeout=90);r.raise_for_status();P.parent.mkdir(parents=True,exist_ok=True);P.write_bytes(r.content)
rows={r['Scientific.Name'].replace('_',' '):r for r in csv.DictReader(P.open())};base=json.loads((R/'data/animalstats/pilot.json').read_text());coveragePath=R/'data/animalstats/existing-coverage.json';base['animals']+=json.loads(coveragePath.read_text())['animals'] if coveragePath.exists() else [];src='tetrapodtraits-201-spatial';d={'animals':[],'photos':[],'traits':[],'values':[],'sources':[{'id':src,'name':'TetrapodTraits 2.0.1 · sourced range and ecology','url':'https://zenodo.org/records/18926700','versionYear':'2026 release; source snapshots specified per category','retrievedAt':'2026-10-10','license':'CC BY 4.0; cite Moura et al. 2024 (PLOS Biology) and Pyron et al. 2025 (Research Square); retain original source attribution','sourceClass':'curated-trait-database'}]};admitted=collections.Counter();held=collections.Counter()
metrics=[
('tt_range_area','Largest mapped range','Smallest mapped range','RangeSize_km2','km²','range','intuitive','range','Area of the published species range map in an equal-area projection (km²), as compiled by TetrapodTraits 2.0.1 from Map of Life. Birds use breeding range only. This is mapped distribution, not occupied territory, population size, migration distance or measured travel.'),
('tt_range_temperature','Lives in the warmest climates','Lives in the coldest climates','AnnuMeanTemp','K','climate-temperature','intuitive','environment','Average annual mean temperature across the species mapped range, from CHELSA v1.2 climate layers. Source values in Celsius × 10 are converted exactly to kelvin for storage; the game displays Celsius. This is average habitat climate, not heat tolerance or body temperature.'),
('tt_range_rainfall','Lives in the rainiest climates','Lives in the driest climates','AnnuPrecip','mm/year','climate-rainfall','intuitive','environment','Average annual precipitation across the species mapped range, from CHELSA v1.2 climate layers. This is habitat rainfall, not water consumption or a tolerance limit.'),
('tt_range_elevation','Lives at higher elevations','Lives at lower elevations','Elevation','m','habitat-elevation','intuitive','environment','Average elevation across the species mapped range, from EarthEnv topographic layers. This is average habitat altitude, not maximum climbing height or the highest recorded individual.'),
('tt_diet_breadth','Most varied diet','Least varied diet','DietBreadth','food groups','diet-breadth','intuitive','diet','Number of broad food groups recorded by TetrapodTraits among 10 defined groups: invertebrates, warm-blooded vertebrates, cold-blooded vertebrates, fish, unspecified vertebrates, carrion, fruit, nectar, seeds and other plant material. Bird and mammal groups require at least 20% relative diet use in EltonTraits. This is diversity of major food groups, not number of prey species.'),
('tt_habitat_breadth','Uses the most habitat types','Uses the fewest habitat types','MajorHabitatSum','habitat types','habitat-breadth','specialist','habitat','Number of major IUCN habitat types recorded for the species in the source snapshot. Only non-imputed habitat records are admitted. It does not measure geographic range size or prove tolerance of habitat loss.'),
('tt_assessed_risk','Most endangered','Least endangered','AssessedStatus','IUCN category','conservation','intuitive','conservation','Assessed IUCN extinction-risk category in TetrapodTraits 2.0.1 (source assessments identify their version). LC=1, NT=2, VU=3, EN=4, CR=5. Data Deficient, unassessed, extinct and model-inferred assessments are excluded. This is a cited assessment snapshot, not a live status feed.')]
risk={'LC':1,'NT':2,'VU':3,'EN':4,'CR':5}
for tid,hi,lo,field,unit,key,kind,family,basis in metrics:
 for suffix,label,direction,counter in [('',hi,'higher_wins','__low'),('__low',lo,'lower_wins','')]:d['traits'].append({'id':tid+suffix,'displayName':label,'definition':basis,'measurementBasis':basis,'direction':direction,'unit':unit,'eligibilityGroups':[],'canonicalSourceId':src,'separationMethod':'distinct_ordinal' if field=='AssessedStatus' else 'positive_ratio_5_percent','prototypeCategory':True,'categoryKind':kind,'metricKey':key,'gameplayFamily':family,'counterTraitId':tid+counter})
 for animal in base['animals']:
  row=rows.get(animal['scientificName'])
  if not row or '_' in row['Scientific.Name'] or not animal['active'] or animal.get('entityType')=='breed' or row['AssessedStatus'] in ['EX','EW']:continue
  if field=='MajorHabitatSum' and row['ImputedMajorHabitat']!='0':held['imputed habitat']+=1;continue
  try:value=risk[row[field]] if field=='AssessedStatus' else float(row[field])
  except (KeyError,ValueError):continue
  if field=='AnnuMeanTemp':value=value/10+273.15
  if not math.isfinite(value) or value<=0:held['nonpositive or missing']+=1;continue
  original=row.get({'DietBreadth':'SourceDiet','MajorHabitatSum':'SourceMajorHabitat','AssessedStatus':'SourceStatus'}.get(field,'')) or {'RangeSize_km2':'Map of Life range maps; equal-area projection','AnnuMeanTemp':'CHELSA v1.2','AnnuPrecip':'CHELSA v1.2','Elevation':'EarthEnv topographic layers'}.get(field,'')
  if not original or 'imput' in original.lower() or 'assumed' in original.lower():held['inferred or missing source']+=1;continue
  notes=f"TetrapodTraits 2.0.1; exact species {row['Scientific.Name']}; original field {field}={row[field]}; source: {original}. Cite Moura et al. 2024, PLOS Biology, doi:10.1371/journal.pbio.3002658 and Pyron et al. 2025, doi:10.21203/rs.3.rs-7556378/v1."
  for suffix in ['', '__low']:d['values'].append({'animalId':animal['id'],'traitId':tid+suffix,'valueNumeric':round(value,6),'unit':unit,'sex':'not applicable','lifeStage':'species distribution or ecology','measurementBasis':basis,'sourceId':src,'observationType':'compiled','confidence':'approved','notes':notes,'uncertaintyStatus':'not-reported'})
  admitted[field]+=1
(R/'data/animalstats/tetrapod-spatial.json').write_text(json.dumps(d)+'\n');(R/'data/animalstats/research/tetrapod-spatial-admission.json').write_text(json.dumps({'sourceVersion':'2.0.1','sourceSpecies':len(rows),'sha256':hashlib.sha256(P.read_bytes()).hexdigest(),'admitted':dict(admitted),'held':dict(held),'excludedFields':['Imputed body mass and length','Mixed litter statistics','Inferred developmental mode','Inferred IUCN threat status','Longevity without wild/captive context','Human pressure model estimates'],'rules':['Exact species only','No taxonomic substitution','No extinct or domestic breed extrapolation','Environmental averages describe mapped habitat, not animal physiology','Bird ranges are breeding ranges','Counter categories share each measurement']},indent=2)+'\n');print(dict(admitted))
