-- GeoStats v14.1
-- Privacy-conscious first-party analytics and Daily generation health.

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  session_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  path text,
  difficulty text,
  challenge_date date,
  value numeric,
  metadata jsonb not null default '{}'::jsonb,
  constraint analytics_events_name_check check (event_name in (
    'page_view','game_started','game_completed','share_clicked',
    'source_opened','account_username_saved','account_signin_requested',
    'account_gate_opened'
  )),
  constraint analytics_events_difficulty_check check (difficulty is null or difficulty in ('easy','normal','expert')),
  constraint analytics_events_session_check check (length(session_id) between 8 and 80),
  constraint analytics_events_path_check check (path is null or length(path) <= 240)
);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_name_created_idx on public.analytics_events(event_name,created_at desc);
create index if not exists analytics_events_session_created_idx on public.analytics_events(session_id,created_at desc);
create index if not exists analytics_events_user_created_idx on public.analytics_events(user_id,created_at desc) where user_id is not null;

alter table public.analytics_events enable row level security;
-- No public policies: events are accepted only through the validated server route.

create table if not exists public.daily_generation_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  challenge_date date not null,
  status text not null check (status in ('completed','failed','repaired')),
  source text not null default 'admin',
  diagnostics jsonb,
  scores jsonb,
  error_message text
);
create index if not exists daily_generation_runs_date_idx on public.daily_generation_runs(challenge_date desc,created_at desc);
alter table public.daily_generation_runs enable row level security;

create or replace view public.analytics_overview_30d
with (security_invoker=true)
as
select
  count(distinct session_id) filter (where event_name='page_view')::bigint as visitors,
  count(*) filter (where event_name='page_view')::bigint as page_views,
  count(*) filter (where event_name='game_started')::bigint as games_started,
  count(*) filter (where event_name='game_completed')::bigint as games_completed,
  count(*) filter (where event_name='share_clicked')::bigint as shares,
  round(avg(value) filter (where event_name='game_completed'),1) as average_score,
  count(distinct user_id) filter (where user_id is not null)::bigint as signed_in_users_seen
from public.analytics_events
where created_at >= now()-interval '30 days';

create or replace view public.analytics_daily_30d
with (security_invoker=true)
as
select
  created_at::date as activity_date,
  event_name,
  difficulty,
  count(*)::bigint as events,
  count(distinct session_id)::bigint as sessions,
  count(distinct user_id) filter (where user_id is not null)::bigint as signed_in_users,
  round(avg(value),1) as average_value
from public.analytics_events
where created_at >= now()-interval '30 days'
group by created_at::date,event_name,difficulty;

grant all on table public.analytics_events to service_role;
grant all on table public.daily_generation_runs to service_role;
grant usage, select on all sequences in schema public to service_role;

grant select on public.analytics_overview_30d to service_role;
grant select on public.analytics_daily_30d to service_role;

commit;
