-- GeoStats v14.2
-- End-to-end source integrity validation. Imports and editorial approval are not
-- enough: a category becomes playable only after its official-source snapshot,
-- stored values, rankings, unit, year, and series identity agree.

begin;

alter table public.stat_categories
  add column if not exists validation_status text not null default 'pending',
  add column if not exists validation_version text,
  add column if not exists validated_at timestamptz,
  add column if not exists validation_reason text,
  add column if not exists source_snapshot_checksum text,
  add column if not exists stored_snapshot_checksum text,
  add column if not exists validated_observation_count integer,
  add column if not exists validation_expected_count integer,
  add column if not exists validation_mismatch_count integer not null default 0,
  add column if not exists validation_ranking_mismatch_count integer not null default 0;

alter table public.stat_categories drop constraint if exists stat_categories_validation_status_check;
alter table public.stat_categories add constraint stat_categories_validation_status_check
  check (validation_status in ('pending','verified','failed','unable_to_verify'));
alter table public.stat_categories drop constraint if exists stat_categories_validation_counts_check;
alter table public.stat_categories add constraint stat_categories_validation_counts_check
  check (
    (validated_observation_count is null or validated_observation_count >= 0)
    and (validation_expected_count is null or validation_expected_count >= 0)
    and validation_mismatch_count >= 0
    and validation_ranking_mismatch_count >= 0
  );

create index if not exists stat_categories_validation_idx
  on public.stat_categories(validation_status,source_organization,validated_at desc);

create table if not exists public.stat_validation_runs (
  id bigint generated by default as identity primary key,
  source_organization text,
  status text not null check (status in ('running','completed','partial','failed')),
  validation_version text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  categories_selected integer not null default 0,
  categories_verified integer not null default 0,
  categories_failed integer not null default 0,
  categories_unable integer not null default 0,
  error_message text,
  details jsonb not null default '{}'::jsonb
);
create index if not exists stat_validation_runs_started_idx on public.stat_validation_runs(started_at desc);

create table if not exists public.stat_category_validation_results (
  id bigint generated by default as identity primary key,
  validation_run_id bigint references public.stat_validation_runs(id) on delete set null,
  category_id text not null references public.stat_categories(id) on delete cascade,
  source_organization text not null,
  validation_status text not null check (validation_status in ('verified','failed','unable_to_verify')),
  validation_version text not null,
  validated_at timestamptz not null default now(),
  common_year smallint,
  expected_observation_count integer,
  stored_observation_count integer,
  compared_observation_count integer,
  value_mismatch_count integer not null default 0,
  ranking_mismatch_count integer not null default 0,
  source_snapshot_checksum text,
  stored_snapshot_checksum text,
  metadata_checks jsonb not null default '{}'::jsonb,
  failure_reason text,
  details jsonb not null default '{}'::jsonb
);
create index if not exists stat_category_validation_results_category_idx
  on public.stat_category_validation_results(category_id,validated_at desc);
create index if not exists stat_category_validation_results_status_idx
  on public.stat_category_validation_results(validation_status,validated_at desc);

create table if not exists public.geostats_feature_flags (
  id text primary key,
  enabled boolean not null default false,
  updated_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);
insert into public.geostats_feature_flags(id,enabled,details)
values ('source_integrity_enforced',false,jsonb_build_object('introducedIn','14.2.0'))
on conflict(id) do nothing;

alter table public.stat_validation_runs enable row level security;
alter table public.stat_category_validation_results enable row level security;
alter table public.geostats_feature_flags enable row level security;
grant all on public.stat_validation_runs to service_role;
grant all on public.stat_category_validation_results to service_role;
grant all on public.geostats_feature_flags to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.source_integrity_is_enforced()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce((select enabled from public.geostats_feature_flags where id='source_integrity_enforced'),false)
$$;

create or replace function public.record_category_validation(
  p_category_id text,
  p_status text,
  p_validation_version text,
  p_common_year integer,
  p_expected_count integer,
  p_stored_count integer,
  p_compared_count integer,
  p_value_mismatch_count integer,
  p_ranking_mismatch_count integer,
  p_source_checksum text,
  p_stored_checksum text,
  p_metadata_checks jsonb,
  p_failure_reason text,
  p_details jsonb,
  p_validation_run_id bigint default null
)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  source_name text;
  group_name text;
begin
  if p_status not in ('verified','failed','unable_to_verify') then
    raise exception 'Invalid validation status %',p_status;
  end if;
  select source_organization,concept_group into source_name,group_name
  from public.stat_categories where id=p_category_id;
  if not found then raise exception 'Unknown stat category %',p_category_id; end if;

  insert into public.stat_category_validation_results(
    validation_run_id,category_id,source_organization,validation_status,validation_version,
    common_year,expected_observation_count,stored_observation_count,compared_observation_count,
    value_mismatch_count,ranking_mismatch_count,source_snapshot_checksum,stored_snapshot_checksum,
    metadata_checks,failure_reason,details
  ) values (
    p_validation_run_id,p_category_id,source_name,p_status,p_validation_version,
    p_common_year,p_expected_count,p_stored_count,p_compared_count,
    greatest(coalesce(p_value_mismatch_count,0),0),greatest(coalesce(p_ranking_mismatch_count,0),0),
    p_source_checksum,p_stored_checksum,coalesce(p_metadata_checks,'{}'::jsonb),p_failure_reason,coalesce(p_details,'{}'::jsonb)
  );

  update public.stat_categories set
    validation_status=p_status,
    validation_version=p_validation_version,
    validated_at=now(),
    validation_reason=case when p_status='verified' then 'Official-source values, metadata, coverage, and rankings matched the stored common-year snapshot.' else coalesce(p_failure_reason,'Source integrity validation did not pass.') end,
    source_snapshot_checksum=p_source_checksum,
    stored_snapshot_checksum=p_stored_checksum,
    validated_observation_count=p_compared_count,
    validation_expected_count=p_expected_count,
    validation_mismatch_count=greatest(coalesce(p_value_mismatch_count,0),0),
    validation_ranking_mismatch_count=greatest(coalesce(p_ranking_mismatch_count,0),0),
    enabled=case when p_status='verified' then enabled else false end,
    eligible_daily=case when p_status='verified' then eligible_daily else false end,
    auto_decision_reason=case
      when p_status='verified' then auto_decision_reason
      else 'Source integrity quarantine: '||coalesce(p_failure_reason,'validation did not pass')
    end,
    metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object(
      'sourceIntegrityStatus',p_status,
      'sourceIntegrityVersion',p_validation_version,
      'sourceSnapshotChecksum',p_source_checksum,
      'storedSnapshotChecksum',p_stored_checksum,
      'sourceIntegrityValidatedAt',now(),
      'sourceIntegrityDetails',coalesce(p_details,'{}'::jsonb)
    ),
    updated_at=now()
  where id=p_category_id;

  perform public.apply_category_governance(p_category_id);
  return p_status;
end;
$$;

-- Duplicate arbitration is source-integrity aware. Failed and unverifiable rows
-- are always excluded. Pending rows remain available only until the one-time
-- full audit is completed and enforcement is explicitly activated.
create or replace function public.refresh_stat_concept_group(p_concept_group text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare chosen text;
declare enforce_integrity boolean:=public.source_integrity_is_enforced();
begin
  if p_concept_group is null or btrim(p_concept_group)='' then return null; end if;

  select category.id into chosen
  from public.stat_categories category
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected'
    and category.auto_qualified=true
    and category.provenance_status='approved'
    and category.independent_validation=true
    and category.curation_status='approved'
    and coalesce(category.credibility_status,'quarantined')<>'quarantined'
    and coalesce(category.credibility_score,0)>=75
    and coalesce(category.objective_status,'uncertain')='objective'
    and coalesce(category.player_quality_status,'blocked')<>'blocked'
    and coalesce(category.verifiability_score,0)>=80
    and coalesce(category.understandability_score,0)>=70
    and coalesce(category.fun_score,0)>=55
    and coalesce(category.validation_status,'pending') not in ('failed','unable_to_verify')
    and (not enforce_integrity or category.validation_status='verified')
  order by
    category.governance_priority asc,
    category.validation_status='verified' desc,
    category.player_quality_status='approved' desc,
    category.verifiability_score desc,
    category.understandability_score desc,
    category.fun_score desc,
    category.credibility_score desc,
    category.quality_score desc,
    category.common_year_coverage desc,
    category.latest_available_year desc nulls last,
    category.id
  limit 1;

  update public.stat_categories category
  set
    enabled=case when category.id=chosen then true else false end,
    eligible_daily=case when category.id=chosen then true else false end,
    review_status=case
      when category.review_status='rejected' then 'rejected'
      when category.validation_status in ('failed','unable_to_verify') then 'candidate'
      when enforce_integrity and category.validation_status<>'verified' then 'needs_review'
      when category.curation_status='excluded' then 'candidate'
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then 'candidate'
      when category.player_quality_status='blocked' then 'candidate'
      when category.id=chosen then 'approved'
      when category.auto_qualified and category.provenance_status='approved' then 'candidate'
      when category.auto_qualified then 'needs_review'
      else 'candidate'
    end,
    duplicate_status=case
      when category.validation_status in ('failed','unable_to_verify')
        or (enforce_integrity and category.validation_status<>'verified')
        or category.curation_status='excluded'
        or category.credibility_status='quarantined'
        or coalesce(category.credibility_score,0)<75
        or category.player_quality_status='blocked' then 'not_eligible'
      when category.id=chosen then 'preferred'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'superseded'
      else 'not_eligible'
    end,
    superseded_by=case when category.id<>chosen and chosen is not null then chosen else null end,
    auto_decision_reason=case
      when category.validation_status in ('failed','unable_to_verify') then 'Source integrity quarantine: '||coalesce(category.validation_reason,'validation did not pass')
      when enforce_integrity and category.validation_status<>'verified' then 'Awaiting official-source integrity validation.'
      when category.curation_status='excluded' then category.curation_reason
      when category.credibility_status='quarantined' or coalesce(category.credibility_score,0)<75 then category.credibility_reason
      when category.player_quality_status='blocked' then category.player_quality_reason
      when category.id=chosen then 'Selected after source integrity, quality, provenance, credibility, objectivity, clarity, fun, and duplicate review.'
      when chosen is not null and category.auto_qualified and category.provenance_status='approved' then 'Passed the gates but was superseded by a stronger near-duplicate.'
      else category.auto_decision_reason
    end,
    updated_at=now()
  where category.concept_group=p_concept_group
    and category.review_status<>'rejected';

  return chosen;
end;
$$;

create or replace function public.apply_category_governance(p_category_id text)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare group_name text;
begin
  perform public.apply_category_curation(p_category_id);
  perform public.apply_category_credibility(p_category_id);
  perform public.apply_category_player_quality(p_category_id);
  select concept_group into group_name from public.stat_categories where id=p_category_id;
  if group_name is null then
    update public.stat_categories set concept_group=id where id=p_category_id;
    group_name:=p_category_id;
  end if;
  return public.refresh_stat_concept_group(group_name);
end;
$$;

create or replace function public.activate_source_integrity_enforcement()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare pending_enabled integer;
declare verified_count integer;
declare quarantined_count integer;
declare row record;
begin
  select count(*) into pending_enabled from public.stat_categories
  where (enabled or eligible_daily)
    and coalesce(validation_status,'pending')<>'verified';
  if pending_enabled>0 then
    raise exception 'Cannot activate source integrity enforcement: % currently playable categories are not verified.',pending_enabled;
  end if;
  update public.geostats_feature_flags
    set enabled=true,updated_at=now(),details=details||jsonb_build_object('activatedAt',now(),'activatedBy','v14.2 audit')
    where id='source_integrity_enforced';
  for row in select distinct concept_group from public.stat_categories where concept_group is not null loop
    perform public.refresh_stat_concept_group(row.concept_group);
  end loop;
  select count(*) into verified_count from public.stat_categories where validation_status='verified';
  select count(*) into quarantined_count from public.stat_categories where validation_status in ('failed','unable_to_verify');
  return jsonb_build_object('enforced',true,'verified',verified_count,'quarantined',quarantined_count);
end;
$$;

create or replace view public.data_integrity_by_source
with (security_invoker=true)
as
select
  source_organization as source,
  count(*)::bigint as categories,
  count(*) filter(where enabled and eligible_daily)::bigint as playable,
  count(*) filter(where validation_status='verified')::bigint as verified,
  count(*) filter(where validation_status='failed')::bigint as failed,
  count(*) filter(where validation_status='unable_to_verify')::bigint as unable_to_verify,
  count(*) filter(where validation_status='pending')::bigint as pending,
  max(validated_at) as last_validated_at
from public.stat_categories
group by source_organization;

create or replace view public.data_integrity_overview
with (security_invoker=true)
as
select
  public.source_integrity_is_enforced() as enforcement_enabled,
  count(*)::bigint as categories,
  count(*) filter(where enabled and eligible_daily)::bigint as playable,
  count(*) filter(where validation_status='verified')::bigint as verified,
  count(*) filter(where validation_status='failed')::bigint as failed,
  count(*) filter(where validation_status='unable_to_verify')::bigint as unable_to_verify,
  count(*) filter(where validation_status='pending')::bigint as pending,
  count(*) filter(where (enabled or eligible_daily) and validation_status<>'verified')::bigint as unverified_playable
from public.stat_categories;

create or replace view public.data_integrity_issues
with (security_invoker=true)
as
select id,title,source_organization,source_dataset,source_indicator_code,validation_status,
  validation_reason,validated_at,common_year,common_year_coverage,validation_expected_count,
  validated_observation_count,validation_mismatch_count,validation_ranking_mismatch_count
from public.stat_categories
where validation_status in ('failed','unable_to_verify')
order by validated_at desc nulls last,source_organization,title;

grant select on public.data_integrity_by_source to service_role;
grant select on public.data_integrity_overview to service_role;
grant select on public.data_integrity_issues to service_role;
revoke all on function public.record_category_validation(text,text,text,integer,integer,integer,integer,integer,integer,text,text,jsonb,text,jsonb,bigint) from public,anon,authenticated;
revoke all on function public.activate_source_integrity_enforcement() from public,anon,authenticated;
grant execute on function public.record_category_validation(text,text,text,integer,integer,integer,integer,integer,integer,text,text,jsonb,text,jsonb,bigint) to service_role;
grant execute on function public.activate_source_integrity_enforcement() to service_role;
grant execute on function public.source_integrity_is_enforced() to service_role;

commit;
