-- geostats-v16.2.6-priority-150-legacy-reaudit
-- First-principles review of the highest-priority generic non-FAOSTAT legacy rejections.
-- Clearing a legacy block does NOT make a category playable; all source, integrity, duplication, editorial and activation gates still apply.
begin;

alter table public.legacy_category_rejections_v16_2_6 drop constraint if exists legacy_category_rejections_v16_2_6_default_decision_check;
alter table public.legacy_category_rejections_v16_2_6 add constraint legacy_category_rejections_v16_2_6_default_decision_check check(default_decision in ('requires_reaudit','cleared_for_reconsideration','confirmed_exclusion'));

create table if not exists public.legacy_rejection_first_principles_reaudit_v16_2_6 (
  legacy_key text primary key references public.legacy_category_rejections_v16_2_6(legacy_key) on delete cascade,
  source_line integer not null unique,
  category_title text not null,
  legacy_source text not null,
  legacy_domain_series text,
  historical_integrity_status text,
  historical_quality text,
  editorial_disposition text not null check(editorial_disposition in ('advance_to_validation','clear_legacy_block_current_path_governs','hold_for_family_curation','retain_exclusion')),
  legacy_guard_action text not null check(legacy_guard_action in ('clear_generic_legacy_block','keep_reaudit_block','confirm_reasoned_exclusion')),
  reason_class text not null,
  first_principles_rationale text not null,
  recommended_next_action text not null,
  linked_tracker_ids text,
  linked_tracker_dispositions text,
  reviewed_at timestamptz not null default now()
);
alter table public.legacy_rejection_first_principles_reaudit_v16_2_6 enable row level security;
revoke all on public.legacy_rejection_first_principles_reaudit_v16_2_6 from public,anon,authenticated;
grant select,insert,update,delete on public.legacy_rejection_first_principles_reaudit_v16_2_6 to service_role;

insert into public.legacy_rejection_first_principles_reaudit_v16_2_6(legacy_key,source_line,category_title,legacy_source,legacy_domain_series,historical_integrity_status,historical_quality,editorial_disposition,legacy_guard_action,reason_class,first_principles_rationale,recommended_next_action,linked_tracker_ids,linked_tracker_dispositions) values
  ('legacy:589',589,'Most asylum seekers originating','UNHCR','Displacement · population:coo:asylum_seekers','verified','95','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Broad, recognizable displacement measure with a distinct player-facing question; the old generic rejection is not a sufficient reason to suppress it.','Use the recovered UNHCR Refugee Data Finder importer; validate coverage/year consistency and then clear the legacy-only blocker.','family:unhcr:most-asylum-seekers-originating','ready_for_source_family_validation'),
  ('legacy:600',600,'Lowest upper-secondary out-of-school rate','UNESCO UIS','Education · ROFST.MOD.3','verified','94','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Out-of-school rates are intuitive, globally meaningful education-access measures; primary and upper-secondary provide meaningfully different stages without keeping every adjacent stage.','Validate the UNESCO UIS source-family rows and retain only these stage anchors unless later playtesting supports more.','family:unesco:lowest-upper-secondary-out-of-school','ready_for_source_family_validation'),
  ('legacy:601',601,'Lowest lower-secondary out-of-school rate','UNESCO UIS','Education · ROFST.MOD.2','verified','94','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:lowest-lower-secondary-out-of-school','ready_for_source_family_validation'),
  ('legacy:606',606,'Highest primary-school completion rate','UNESCO UIS','Education · CR.MOD.1','','94','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','',''),
  ('legacy:607',607,'Highest upper-secondary completion rate','UNESCO UIS','Education · CR.MOD.3','','94','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Upper-secondary completion is a recognizable education outcome and is more discriminating than another near-universal primary enrollment measure.','Resolve the exact UIS completion series in the importer, validate coverage, and use a plain-English title/definition.','',''),
  ('legacy:608',608,'Modeled lower-secondary completion rate','UNESCO UIS','Education · CR.MOD.2','','94','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','',''),
  ('legacy:609',609,'Most asylum seekers hosted','UNHCR','Displacement · population:coa:asylum_seekers','verified','94','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Broad, recognizable displacement measure with a distinct player-facing question; the old generic rejection is not a sufficient reason to suppress it.','Use the recovered UNHCR Refugee Data Finder importer; validate coverage/year consistency and then clear the legacy-only blocker.','family:unhcr:most-asylum-seekers-hosted','ready_for_source_family_validation'),
  ('legacy:795',795,'Highest urban population share','World Bank','Population · SP.URB.TOTL.IN.ZS','verified','90','hold_for_family_curation','keep_reaudit_block','definition_overlap','“Urban” is definition-sensitive and the new WUP family distinguishes cities, towns and rural areas; this old aggregate wording risks mixing a different urbanization concept with the newer taxonomy.','Keep blocked until the WUP urban/city/town definition strategy is finalized; prefer explicit city/town/rural wording.','',''),
  ('legacy:797',797,'Largest rural population','World Bank','Population · SP.RUR.TOTL','verified','90','advance_to_validation','clear_generic_legacy_block','source_superseded_concept_retained','Largest rural population is intuitive and distinct; the concept remains strong, but UN WUP 2025 is now the preferred purpose-built population source.','Use the recovered UN WUP 2025 rural-population family and clear only the historical generic rejection, not the normal source/quality gates.','family:unwup:rural-population','ready_for_source_family_validation'),
  ('legacy:798',798,'Largest urban population','World Bank','Population · SP.URB.TOTL','verified','90','hold_for_family_curation','keep_reaudit_block','definition_overlap','“Urban” is definition-sensitive and the new WUP family distinguishes cities, towns and rural areas; this old aggregate wording risks mixing a different urbanization concept with the newer taxonomy.','Keep blocked until the WUP urban/city/town definition strategy is finalized; prefer explicit city/town/rural wording.','',''),
  ('legacy:801',801,'Farthest from the equator','Natural Earth','Geography · farthest-from-equator','','90','hold_for_family_curation','keep_reaudit_block','metric_definition_needed','Interesting in principle, but “farthest from the equator” is ambiguous unless the representative point/territorial extent method is explicit.','Keep blocked until the exact geometry statistic is defined and tested against edge cases.','',''),
  ('legacy:805',805,'Largest east-west span','Natural Earth','Geography · largest-east-west-span','','90','advance_to_validation','clear_generic_legacy_block','physical_geography_anchor','Intuitive map-based physical-geography question that adds badly needed non-economic breadth; the metric can be derived reproducibly from sovereign geometry.','Validate the geodesic/geometry definition, edge cases and sovereign-country mapping; northernmost/southernmost already have fail-closed importer paths.','',''),
  ('legacy:806',806,'Largest geographic span','Natural Earth','Geography · largest-geographic-span','','90','retain_exclusion','confirm_reasoned_exclusion','near_duplicate_ambiguous','Generic “geographic span” collapses different east-west/north-south dimensions and is less interpretable than the two explicit span categories.','Keep excluded; use explicit east-west and north-south span metrics instead.','',''),
  ('legacy:807',807,'Largest north-south span','Natural Earth','Geography · largest-north-south-span','','90','advance_to_validation','clear_generic_legacy_block','physical_geography_anchor','Intuitive map-based physical-geography question that adds badly needed non-economic breadth; the metric can be derived reproducibly from sovereign geometry.','Validate the geodesic/geometry definition, edge cases and sovereign-country mapping; northernmost/southernmost already have fail-closed importer paths.','',''),
  ('legacy:809',809,'Northernmost country','Natural Earth','Geography · northernmost-country','','90','advance_to_validation','clear_generic_legacy_block','physical_geography_anchor','Intuitive map-based physical-geography question that adds badly needed non-economic breadth; the metric can be derived reproducibly from sovereign geometry.','Validate the geodesic/geometry definition, edge cases and sovereign-country mapping; northernmost/southernmost already have fail-closed importer paths.','candidate:001','ready_for_validated_import'),
  ('legacy:810',810,'Southernmost country','Natural Earth','Geography · southernmost-country','','90','advance_to_validation','clear_generic_legacy_block','physical_geography_anchor','Intuitive map-based physical-geography question that adds badly needed non-economic breadth; the metric can be derived reproducibly from sovereign geometry.','Validate the geodesic/geometry definition, edge cases and sovereign-country mapping; northernmost/southernmost already have fail-closed importer paths.','candidate:002','ready_for_validated_import'),
  ('legacy:813',813,'Highest clean-cooking-fuel access','WHO','Infrastructure · PHE_HHAIR_POP_CLEAN_FUELS','','90','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','',''),
  ('legacy:816',816,'Highest employment-to-population ratio','ILOSTAT','Labor · EMP_2WAP_SEX_AGE_RT_A','verified','90','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:highest-employment-population-ratio','ready_for_source_family_validation'),
  ('legacy:817',817,'Highest labor-income share of GDP','ILOSTAT','Labor · SDG_1041_NOC_RT_A','verified','90','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:highest-labor-income-share','ready_for_source_family_validation'),
  ('legacy:818',818,'Highest output per worker','ILOSTAT','Economy · GDP_205U_NOC_NB_A','failed','90','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:highest-output-per-worker','ready_for_source_family_validation'),
  ('legacy:820',820,'Lowest unemployment','World Bank','Labor · SL.UEM.TOTL.ZS','verified','90','advance_to_validation','clear_generic_legacy_block','high_value_source_repair','National unemployment is highly recognizable and useful, but the existing tracker correctly requires a repaired authoritative labor-statistics path rather than reviving the old WDI row blindly.','Keep fail-closed until a validated authoritative labor source/method is resolved; legacy status alone should no longer veto the concept.','candidate:178','not_shipped_validation_or_definition_unresolved'),
  ('legacy:846',846,'Highest account ownership at a financial institution or with a mobile-money-service provider, young adults','World Bank','Economy · FX.OWN.TOTL.YG.ZS','','90','retain_exclusion','confirm_reasoned_exclusion','subgroup_slice','Demographic subgroup slice of a broader access/use concept; the default catalog should prefer the all-population measure unless the subgroup itself is the central idea.','Keep excluded from the core playable catalog.','',''),
  ('legacy:896',896,'Highest industry share of GDP','World Bank','Economy · NV.IND.TOTL.ZS','verified','88','hold_for_family_curation','keep_reaudit_block','macro_density','Industry and services shares of GDP are understandable, but the catalog is already economy-heavy and these complementary sector shares should be curated together rather than added automatically.','Hold for economy-family curation; promote only if sector composition materially improves board variety.','',''),
  ('legacy:897',897,'Highest services share of GDP','World Bank','Economy · NV.SRV.TOTL.ZS','verified','88','hold_for_family_curation','keep_reaudit_block','macro_density','Industry and services shares of GDP are understandable, but the catalog is already economy-heavy and these complementary sector shares should be curated together rather than added automatically.','Hold for economy-family curation; promote only if sector composition materially improves board variety.','',''),
  ('legacy:899',899,'Fastest labor-productivity growth','ILOSTAT','Economy · SDG_0821_NOC_RT_A','failed','88','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:fastest-productivity-growth','ready_for_source_family_validation'),
  ('legacy:946',946,'Highest methane (CH4) emissions (total) excluding LULUCF','World Bank','Environment · EN.GHG.CH4.ZG.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:950',950,'Highest nitrous oxide (N2O) emissions (total) excluding LULUCF','World Bank','Environment · EN.GHG.N2O.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:951',951,'Highest nitrous oxide (N2O) emissions (total) excluding LULUCF','World Bank','Environment · EN.GHG.N2O.ZG.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:956',956,'Highest total greenhouse gas emissions excluding LULUCF','World Bank','Environment · EN.GHG.TOT.ZG.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:959',959,'Highest carbon dioxide (CO2) emissions (total) excluding LULUCF','World Bank','Environment · EN.GHG.CO2.ZG.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:966',966,'Highest internet usage','World Bank','Technology · IT.NET.USER.ZS','verified','86','advance_to_validation','clear_generic_legacy_block','source_superseded_concept_retained','Internet-use share is a broad, intuitive technology-access measure; it is meaningfully different from secure-server counts and school internet access.','Use the recovered infrastructure/internet-use source-family path, validate coverage/year consistency, and prefer the clearer “internet-use share” wording.','',''),
  ('legacy:968',968,'Highest methane (CH4) emissions from Fugitive Emissions (Energy)','World Bank','Environment · EN.GHG.CH4.FE.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:969',969,'Highest methane (CH4) emissions from Industrial Combustion (Energy)','World Bank','Environment · EN.GHG.CH4.IC.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:970',970,'Highest methane (CH4) emissions from Power Industry (Energy)','World Bank','Environment · EN.GHG.CH4.PI.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:972',972,'Highest nitrous oxide (N2O) emissions from Building (Energy)','World Bank','Environment · EN.GHG.N2O.BU.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:973',973,'Highest nitrous oxide (N2O) emissions from Industrial Combustion (Energy)','World Bank','Environment · EN.GHG.N2O.IC.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:974',974,'Highest nitrous oxide (N2O) emissions from Power Industry (Energy)','World Bank','Environment · EN.GHG.N2O.PI.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:975',975,'Highest nitrous oxide (N2O) emissions from Transport (Energy)','World Bank','Environment · EN.GHG.N2O.TR.MT.CE.AR5','verified','86','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:976',976,'Highest carbon intensity of GDP','World Bank','Environment · EN.GHG.CO2.RT.GDP.PP.KD','verified','86','hold_for_family_curation','keep_reaudit_block','emissions_methodology_density','Carbon intensity is more distinct than raw emissions totals, but it still needs a clearly defined denominator/method and must be considered against the intentionally pruned emissions family.','Keep quarantined until the carbon-intensity methodology is resolved and emissions-family density is reviewed.','',''),
  ('legacy:1016',1016,'Highest nitrous oxide (N2O) emissions from Fugitive Emissions (Energy)','World Bank','Environment · EN.GHG.N2O.FE.MT.CE.AR5','verified','85','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1045',1045,'Largest exports','World Bank','Economy · NE.EXP.GNFS.CD','verified','84','retain_exclusion','confirm_reasoned_exclusion','duplicate_or_ambiguous_macro','Generic “exports/imports” duplicates clearer existing trade categories and is ambiguous about goods/services/primary income scope.','Keep excluded; use the already retained explicitly defined trade categories.','',''),
  ('legacy:1046',1046,'Largest imports','World Bank','Economy · NE.IMP.GNFS.CD','verified','84','retain_exclusion','confirm_reasoned_exclusion','duplicate_or_ambiguous_macro','Generic “exports/imports” duplicates clearer existing trade categories and is ambiguous about goods/services/primary income scope.','Keep excluded; use the already retained explicitly defined trade categories.','',''),
  ('legacy:1075',1075,'Highest carbon dioxide (CO2) emissions from Fugitive Emissions (Energy)','World Bank','Environment · EN.GHG.CO2.FE.MT.CE.AR5','verified','83','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1105',1105,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.ZS','verified','83','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1106',1106,'Highest general government final consumption expenditure','World Bank','Economy · NE.CON.GOVT.ZS','verified','83','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1107',1107,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.CD','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1108',1108,'Highest government consumption','World Bank','Government · NE.CON.GOVT.CD','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1109',1109,'Highest gross national expenditure','World Bank','Economy · NE.DAB.TOTL.ZS','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1110',1110,'Highest households and NPISHs final consumption expenditure','World Bank','Economy · NE.CON.PRVT.ZS','verified','83','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1111',1111,'Highest gross national expenditure','World Bank','Economy · NE.DAB.TOTL.CD','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1112',1112,'Highest household consumption','World Bank','Economy · NE.CON.PRVT.CD','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1113',1113,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.KD','failed','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1115',1115,'Highest households and NPISHs Final consumption expenditure per capita, PPP','World Bank','Development · NE.CON.PCAP.PP.KD','verified','83','advance_to_validation','clear_generic_legacy_block','broad_intuitive_rewrite','Household consumption per person at PPP is a meaningful living-standard concept, unlike the many total/local-currency national-accounts variants around it; the player-facing copy must be simplified.','Validate a comparable PPP per-capita series and rewrite as plain-English household consumption per person; keep all adjacent aggregate variants excluded/held.','',''),
  ('legacy:1116',1116,'Highest households and NPISHs Final consumption expenditure, PPP','World Bank','Economy · NE.CON.PRVT.PP.KD','verified','83','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1154',1154,'Highest fixed telephone subscriptions per 100 people','World Bank','Technology · IT.MLT.MAIN.P2','verified','82','retain_exclusion','confirm_reasoned_exclusion','low_marginal_value_near_duplicate','Fixed-line subscriptions per 100 adds limited current-world value and sits next to an already retained fixed-telephone category; it is not a priority use of catalog space.','Keep excluded unless future historical/technology curation creates a specific need.','',''),
  ('legacy:1155',1155,'Largest agricultural land area','World Bank','Agriculture · AG.LND.AGRI.K2','verified','82','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1157',1157,'Most separate land areas','Natural Earth','Geography · most-separate-land-areas','','82','retain_exclusion','confirm_reasoned_exclusion','arbitrary_threshold_niche','Counting separate land areas—especially “large” areas—depends on arbitrary geometry/threshold choices and is less intuitive than stronger map-based geography concepts.','Keep excluded from the core catalog.','',''),
  ('legacy:1163',1163,'Highest primary-school enrollment','UNESCO UIS','Education · GER.1','verified','82','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-primary-enrollment','ready_for_source_family_validation'),
  ('legacy:1166',1166,'Highest carbon dioxide (CO2) net fluxes from LULUCF - Forest Land','World Bank','Environment · EN.GHG.CO2.LU.FL.MT.CE.AR5','verified','82','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1168',1168,'Most cereal produced','World Bank','Agriculture · AG.PRD.CREL.MT','verified','82','clear_legacy_block_current_path_governs','clear_generic_legacy_block','superseded_source_existing_primary_path','The old World Bank cereal-production path should stay retired, but that is not a concept-level veto: a clearer FAOSTAT cereal-production category is already retained under the shared gates.','Clear the stale legacy-title/semantic blocker so the existing FAOSTAT category is governed by current shared quality and duplication gates; do not revive the World Bank route.','',''),
  ('legacy:1169',1169,'Highest cereal yield','World Bank','Agriculture · AG.YLD.CREL.KG','verified','82','retain_exclusion','confirm_reasoned_exclusion','superseded_primary_source','Cereal production/yield is better sourced directly from FAOSTAT and would add another agriculture variant in an already saturated domain.','Keep this World Bank route excluded; only reconsider the concept through curated primary-source agriculture coverage if it is distinct enough.','',''),
  ('legacy:1170',1170,'Highest total greenhouse gas emissions including LULUCF','World Bank','Environment · EN.GHG.ALL.LU.MT.CE.AR5','verified','82','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1173',1173,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.CN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1174',1174,'Highest general government final consumption expenditure','World Bank','Economy · NE.CON.GOVT.CN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1177',1177,'Highest investment share','World Bank','Economy · NE.GDI.TOTL.ZS','verified','82','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1178',1178,'Highest gross capital formation','World Bank','Economy · NE.GDI.TOTL.CD','verified','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','existing:NE.GDI.TOTL.CN','blocked_re_source'),
  ('legacy:1179',1179,'Highest gross national expenditure','World Bank','Economy · NE.DAB.TOTL.CN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1180',1180,'Highest households and NPISHs Final consumption expenditure','World Bank','Economy · NE.CON.PRVT.CN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1181',1181,'Highest households and NPISHs final consumption expenditure: linked series','World Bank','Economy · NE.CON.PRVT.CN.AD','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1182',1182,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.KN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1184',1184,'Highest general government final consumption expenditure','World Bank','Economy · NE.CON.GOVT.KN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1185',1185,'Highest households and NPISHs Final consumption expenditure','World Bank','Economy · NE.CON.PRVT.KN','verified','82','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1187',1187,'Highest households and NPISHs Final consumption expenditure','World Bank','Economy · NE.CON.PRVT.KD','failed','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1188',1188,'Highest households and NPISHs Final consumption expenditure per capita','World Bank','Economy · NE.CON.PRVT.PC.KD','failed','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1189',1189,'Highest general government final consumption expenditure','World Bank','Economy · NE.CON.GOVT.KD','failed','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1190',1190,'Highest gross national expenditure deflator','World Bank','Economy · NE.DAB.DEFL.ZS','failed','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1193',1193,'Highest households and NPISHs Final consumption expenditure per capita, PPP','World Bank','Development · NE.CON.PCAP.PP.CD','verified','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1194',1194,'Highest households and NPISHs Final consumption expenditure, PPP','World Bank','Economy · NE.CON.PRVT.PP.CD','verified','82','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1196',1196,'Highest gross savings rate','World Bank','Economy · NY.GNS.ICTR.ZS','verified','82','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1209',1209,'Highest carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires','World Bank','Environment · EN.GHG.CO2.LU.MT.CE.AR5','verified','81','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1212',1212,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.ZS','verified','81','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1213',1213,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.CN','verified','81','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1214',1214,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.CD','verified','81','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1215',1215,'Highest gross national expenditure','World Bank','Economy · NE.DAB.TOTL.KN','verified','81','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1217',1217,'Highest gross national expenditure','World Bank','Economy · NE.DAB.TOTL.KD','failed','81','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1255',1255,'Most large separate land areas','Natural Earth','Geography · most-large-land-areas','','80','retain_exclusion','confirm_reasoned_exclusion','arbitrary_threshold_niche','Counting separate land areas—especially “large” areas—depends on arbitrary geometry/threshold choices and is less intuitive than stronger map-based geography concepts.','Keep excluded from the core catalog.','',''),
  ('legacy:1256',1256,'Highest final consumption expenditure','World Bank','Economy · NE.CON.TOTL.KD.ZG','verified','80','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1257',1257,'Highest households and NPISHs Final consumption expenditure','World Bank','Economy · NE.CON.PRVT.KD.ZG','verified','80','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1258',1258,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.KN','verified','80','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1259',1259,'Highest gross capital formation','World Bank','Economy · NE.GDI.TOTL.KD','failed','80','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','existing:NE.GDI.TOTL.CN','blocked_re_source'),
  ('legacy:1260',1260,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.KD','failed','80','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1288',1288,'Highest carbon dioxide (CO2) net fluxes from LULUCF - Deforestation','World Bank','Environment · EN.GHG.CO2.LU.DF.MT.CE.AR5','verified','79','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1289',1289,'Highest general government final consumption expenditure','World Bank','Economy · NE.CON.GOVT.KD.ZG','verified','79','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1290',1290,'Fastest households and NPISHs Final consumption expenditure per capita growth','World Bank','Economy · NE.CON.PRVT.PC.KD.ZG','verified','79','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1324',1324,'Lowest primary out-of-school rate','UNESCO UIS','Education · ROFST.1.CP','verified','78','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Out-of-school rates are intuitive, globally meaningful education-access measures; primary and upper-secondary provide meaningfully different stages without keeping every adjacent stage.','Validate the UNESCO UIS source-family rows and retain only these stage anchors unless later playtesting supports more.','family:unesco:lowest-primary-out-of-school','ready_for_source_family_validation'),
  ('legacy:1357',1357,'Highest secondary-school enrollment','UNESCO UIS','Education · GER.2T3','verified','77','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-secondary-enrollment','ready_for_source_family_validation'),
  ('legacy:1359',1359,'Highest gross fixed capital formation','World Bank','Economy · NE.GDI.FTOT.KD.ZG','verified','77','retain_exclusion','confirm_reasoned_exclusion','macro_overproliferation','One of many national-accounts total/constant-price/growth variants with low marginal player value, jargon-heavy naming, or a near-duplicate preferred alternative; economy is already overrepresented.','Keep excluded; do not rebuild the old national-accounts matrix. Reconsider only a separately justified plain-English concept.','',''),
  ('legacy:1442',1442,'Highest education spending share of GDP','UNESCO UIS','Government · XGDP.FSGOV','verified','75','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Distinct, understandable education/science-system dimension that adds breadth beyond enrollment/completion without being a demographic slice.','Validate the recovered UIS series and coverage; keep fail-closed until the source-family gate passes.','family:unesco:highest-education-spending-gdp','ready_for_source_family_validation'),
  ('legacy:1443',1443,'Highest tertiary enrollment','UNESCO UIS','Education · GER.5T8','verified','75','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Distinct, understandable education/science-system dimension that adds breadth beyond enrollment/completion without being a demographic slice.','Validate the recovered UIS series and coverage; keep fail-closed until the source-family gate passes.','family:unesco:highest-tertiary-enrollment','ready_for_source_family_validation'),
  ('legacy:1455',1455,'Largest sports-equipment exports','UN Comtrade','Trade · 9506','verified','75','retain_exclusion','confirm_reasoned_exclusion','product_specific_trade_niche','Sports-equipment exports is a narrow product-trade slice and the product decision explicitly removed it; it does not justify more economy/trade density.','Keep excluded; do not restore through another trade source.','',''),
  ('legacy:1488',1488,'Highest universal-health-coverage score','WHO','Healthcare · UHC_AVAILABILITY_SCORE','failed','74','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:highest-uhc-service-coverage','ready_for_source_family_validation'),
  ('legacy:1492',1492,'Lowest average rainfall','World Bank','Climate · AG.LND.PRCP.MM','failed','74','advance_to_validation','clear_generic_legacy_block','high_value_source_repair','Average rainfall is intuitive physical-world knowledge and belongs in a weak catalog domain; the historical WDI integrity failure is a source-path problem, not a reason to discard the concept.','Use a validated climate source rather than the failed historical path; resolve definition/year aggregation before activation.','',''),
  ('legacy:1547',1547,'Lowest youth NEET rate','ILOSTAT','Labor · EIP_NEET_SEX_RT_A','verified','72','retain_exclusion','confirm_reasoned_exclusion','specialized_or_jargon','NEET/time-related-underemployment terminology is specialized and less immediately interpretable than stronger labor-market measures; the core catalog should not multiply technical labor variants.','Keep excluded from the core playable catalog.','family:ilostat:lowest-neet-rate','ready_for_source_family_validation'),
  ('legacy:1548',1548,'Highest outbound student mobility','UNESCO UIS','Education · MOR.5T8.40505','verified','72','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Distinct, understandable education/science-system dimension that adds breadth beyond enrollment/completion without being a demographic slice.','Validate the recovered UIS series and coverage; keep fail-closed until the source-family gate passes.','family:unesco:highest-outbound-student-mobility','ready_for_source_family_validation'),
  ('legacy:1557',1557,'Highest carbon dioxide (CO2) net fluxes from LULUCF - Other Land','World Bank','Environment · EN.GHG.CO2.LU.OL.MT.CE.AR5','verified','72','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1602',1602,'Lowest diabetes death rate','WHO','Health · SA_0000001440','verified','70','hold_for_family_curation','keep_reaudit_block','cause_specific_health_density','Understandable cause-specific mortality measure, but shipping multiple disease-by-disease death-rate categories risks replacing breadth with a health-cause matrix.','Hold for health-family curation; promote only a small number of the most recognizable disease outcomes.','family:who:lowest-diabetes-death-rate','ready_for_source_family_validation'),
  ('legacy:1604',1604,'Lowest time-related underemployment','ILOSTAT','Labor · EMP_XTRU_SEX_RT_A','verified','70','retain_exclusion','confirm_reasoned_exclusion','specialized_or_jargon','NEET/time-related-underemployment terminology is specialized and less immediately interpretable than stronger labor-market measures; the core catalog should not multiply technical labor variants.','Keep excluded from the core playable catalog.','family:ilostat:lowest-time-underemployment','hold_for_individual_editorial_review'),
  ('legacy:1636',1636,'Lowest primary-school repetition rate','UNESCO UIS','Education · REPR.1.G1.CP','verified','69','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:lowest-primary-repetition','ready_for_source_family_validation'),
  ('legacy:1637',1637,'Highest share of women in management','ILOSTAT','Labor · SDG_0552_NOC_RT_A','verified','69','advance_to_validation','clear_generic_legacy_block','broad_labor_anchor','Distinct and reasonably intuitive labor-market/workplace measure that broadens the catalog beyond unemployment and output statistics.','Validate ILOSTAT series definitions/coverage and use plain-English copy before activation.','family:ilostat:highest-women-management','ready_for_source_family_validation'),
  ('legacy:1638',1638,'Highest school internet access','UNESCO UIS','Technology · SCHBSP.1.WINTERN','verified','69','advance_to_validation','clear_generic_legacy_block','infrastructure_breadth','Concrete school-infrastructure measure that players can readily interpret; selected as an anchor from a larger cluster rather than shipping every closely related facility indicator.','Validate the UIS school-infrastructure series; preserve family caps so internet/electricity/sanitation do not proliferate into a near-duplicate block.','family:unesco:highest-school-internet','ready_for_source_family_validation'),
  ('legacy:1671',1671,'Highest school computer access','UNESCO UIS','Technology · SCHBSP.1.WCOMPUT','verified','68','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-school-computers','ready_for_source_family_validation'),
  ('legacy:1672',1672,'Lowest cancer death rate','WHO','Health · SA_0000001438','verified','68','hold_for_family_curation','keep_reaudit_block','cause_specific_health_density','Understandable cause-specific mortality measure, but shipping multiple disease-by-disease death-rate categories risks replacing breadth with a health-cause matrix.','Hold for health-family curation; promote only a small number of the most recognizable disease outcomes.','family:who:lowest-cancer-death-rate','ready_for_source_family_validation'),
  ('legacy:1673',1673,'Lowest informal-employment rate','ILOSTAT','Labor · EMP_NIFL_SEX_RT_A','verified','68','advance_to_validation','clear_generic_legacy_block','broad_labor_anchor','Distinct and reasonably intuitive labor-market/workplace measure that broadens the catalog beyond unemployment and output statistics.','Validate ILOSTAT series definitions/coverage and use plain-English copy before activation.','family:ilostat:lowest-informal-employment','ready_for_source_family_validation'),
  ('legacy:1682',1682,'Most internally displaced people','UNHCR','Displacement · population:coa:idps','verified','68','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Broad, recognizable displacement measure with a distinct player-facing question; the old generic rejection is not a sufficient reason to suppress it.','Use the recovered UNHCR Refugee Data Finder importer; validate coverage/year consistency and then clear the legacy-only blocker.','family:unhcr:most-internally-displaced-people','ready_for_source_family_validation'),
  ('legacy:1687',1687,'Longest average working week','ILOSTAT','Labor · HOW_UEES_SEX_NB_A','verified','67','advance_to_validation','clear_generic_legacy_block','broad_labor_anchor','Distinct and reasonably intuitive labor-market/workplace measure that broadens the catalog beyond unemployment and output statistics.','Validate ILOSTAT series definitions/coverage and use plain-English copy before activation.','family:ilostat:longest-working-week','ready_for_source_family_validation'),
  ('legacy:1688',1688,'Most researchers per million people','UNESCO UIS','Science · RESDEN.INHAB.TFTE','verified','67','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Distinct, understandable education/science-system dimension that adds breadth beyond enrollment/completion without being a demographic slice.','Validate the recovered UIS series and coverage; keep fail-closed until the source-family gate passes.','family:unesco:most-researchers','ready_for_source_family_validation'),
  ('legacy:1701',1701,'Highest school electricity access','UNESCO UIS','Infrastructure · SCHBSP.1.WELEC','verified','66','advance_to_validation','clear_generic_legacy_block','infrastructure_breadth','Concrete school-infrastructure measure that players can readily interpret; selected as an anchor from a larger cluster rather than shipping every closely related facility indicator.','Validate the UIS school-infrastructure series; preserve family caps so internet/electricity/sanitation do not proliferate into a near-duplicate block.','family:unesco:highest-school-electricity','ready_for_source_family_validation'),
  ('legacy:1720',1720,'Highest school drinking-water access','UNESCO UIS','Infrastructure · SCHBSP.1.WWATA','verified','65','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-school-drinking-water','ready_for_source_family_validation'),
  ('legacy:1721',1721,'Highest school handwashing access','UNESCO UIS','Infrastructure · SCHBSP.1.WWASH','verified','65','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-school-handwashing','ready_for_source_family_validation'),
  ('legacy:1729',1729,'Highest individuals using the Internet, female','World Bank','Infrastructure · IT.NET.USER.FE.ZS','','65','retain_exclusion','confirm_reasoned_exclusion','subgroup_slice','Demographic subgroup slice of a broader access/use concept; the default catalog should prefer the all-population measure unless the subgroup itself is the central idea.','Keep excluded from the core playable catalog.','',''),
  ('legacy:1730',1730,'Highest individuals using the Internet, male','World Bank','Infrastructure · IT.NET.USER.MA.ZS','','65','retain_exclusion','confirm_reasoned_exclusion','subgroup_slice','Demographic subgroup slice of a broader access/use concept; the default catalog should prefer the all-population measure unless the subgroup itself is the central idea.','Keep excluded from the core playable catalog.','',''),
  ('legacy:1775',1775,'Most refugees returned home','UNHCR','Displacement · solutions:coo:returned_refugees','verified','64','hold_for_family_curation','keep_reaudit_block','family_density_specialty','Understandable, but it is a narrower solutions/returns measure and adds less breadth than the core asylum/refugee/displacement stock categories.','Keep quarantined until the UNHCR family is curated as a whole and a specialty slot is justified.','family:unhcr:most-refugees-returned-home','ready_for_source_family_validation'),
  ('legacy:1783',1783,'Highest school sanitation access','UNESCO UIS','Infrastructure · SCHBSP.1.WTOILA','verified','63','advance_to_validation','clear_generic_legacy_block','infrastructure_breadth','Concrete school-infrastructure measure that players can readily interpret; selected as an anchor from a larger cluster rather than shipping every closely related facility indicator.','Validate the UIS school-infrastructure series; preserve family caps so internet/electricity/sanitation do not proliferate into a near-duplicate block.','family:unesco:highest-school-sanitation','ready_for_source_family_validation'),
  ('legacy:1784',1784,'Lowest youth unemployment rate','ILOSTAT','Labor · UNE_3EAP_SEX_AGE_DSB_RT_A','','63','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:lowest-youth-unemployment','ready_for_source_family_validation'),
  ('legacy:1796',1796,'Highest skilled birth-attendance rate','WHO','Maternal Health · MDG_0000000025','','62','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:highest-skilled-birth-attendance','ready_for_source_family_validation'),
  ('legacy:1805',1805,'Highest gross fixed capital formation, private sector','World Bank','Economy · NE.GDI.FPRV.CN','','62','retain_exclusion','confirm_reasoned_exclusion','cross_country_comparability_invalid','Absolute local-currency or linked/local-currency series is not valid for direct cross-country ranking; this is a hard comparability failure, not merely an old editorial preference.','Keep excluded under the permanent local-currency comparability gate.','',''),
  ('legacy:1806',1806,'Highest gross fixed capital formation, private sector','World Bank','Economy · NE.GDI.FPRV.ZS','','62','hold_for_family_curation','keep_reaudit_block','macro_or_landuse_curation','Potentially understandable after careful naming, but it sits in an already dense macro/land-use family and is not strong enough to clear the legacy block without comparing nearby alternatives.','Hold for family-level editorial curation; prefer the single clearest, most comparable representative metric rather than multiple accounting variants.','',''),
  ('legacy:1816',1816,'Most other people needing international protection','UNHCR','Displacement · population:coa:oip','','61','retain_exclusion','confirm_reasoned_exclusion','specialized_or_jargon','Too specialized for the core playable catalog: the label depends on UNHCR-specific status terminology or a narrow return-flow subcategory rather than broadly recognizable world knowledge.','Keep excluded; do not reactivate merely because the UNHCR source now validates.','family:unhcr:most-other-people-needing-protection','ready_for_source_family_validation'),
  ('legacy:1817',1817,'Highest survival to the last grade of primary school','UNESCO UIS','Education · SR.1.GLAST.CP','verified','60','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-primary-survival','ready_for_source_family_validation'),
  ('legacy:1819',1819,'Highest lower-secondary reading proficiency','UNESCO UIS','Education · READ.LOWERSEC','verified','60','advance_to_validation','clear_generic_legacy_block','learning_outcome_anchor','Reading and mathematics proficiency are distinct, recognizable learning outcomes; lower-secondary is retained as the common stage anchor to avoid four stage-by-subject variants.','Validate UIS assessment comparability and country coverage; do not automatically add the corresponding primary-stage duplicates.','family:unesco:highest-reading-proficiency-lower-secondary','ready_for_source_family_validation'),
  ('legacy:1826',1826,'Most internally displaced people returned','UNHCR','Displacement · solutions:coa:returned_idps','','60','retain_exclusion','confirm_reasoned_exclusion','specialized_or_jargon','Too specialized for the core playable catalog: the label depends on UNHCR-specific status terminology or a narrow return-flow subcategory rather than broadly recognizable world knowledge.','Keep excluded; do not reactivate merely because the UNHCR source now validates.','family:unhcr:most-returned-idps','ready_for_source_family_validation'),
  ('legacy:1827',1827,'Highest youth literacy rate','UNESCO UIS','Education · LR.AG15T24','','59','retain_exclusion','confirm_reasoned_exclusion','subgroup_slice','Youth literacy is an age-sliced variant of the broader literacy concept; the catalog should prefer adult/general literacy rather than multiplying demographic variants.','Keep excluded unless a future mode explicitly calls for demographic subgroup categories.','family:unesco:highest-youth-literacy','ready_for_source_family_validation'),
  ('legacy:1830',1830,'Highest primary mathematics proficiency','UNESCO UIS','Education · MATH.PRIMARY','verified','58','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-math-proficiency-primary','ready_for_source_family_validation'),
  ('legacy:1832',1832,'Highest lower-secondary mathematics proficiency','UNESCO UIS','Education · MATH.LOWERSEC','verified','58','advance_to_validation','clear_generic_legacy_block','learning_outcome_anchor','Reading and mathematics proficiency are distinct, recognizable learning outcomes; lower-secondary is retained as the common stage anchor to avoid four stage-by-subject variants.','Validate UIS assessment comparability and country coverage; do not automatically add the corresponding primary-stage duplicates.','family:unesco:highest-math-proficiency-lower-secondary','ready_for_source_family_validation'),
  ('legacy:1857',1857,'Highest adult literacy rate','UNESCO UIS','Education · LR.AG15T99','','57','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Adult literacy is a broad, familiar national outcome and is preferable to narrower age-slice variants.','Resolve/validate the current UIS literacy series and coverage before activation.','family:unesco:highest-adult-literacy','ready_for_source_family_validation'),
  ('legacy:1878',1878,'Highest carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil','World Bank','Environment · EN.GHG.CO2.LU.OS.MT.CE.AR5','','55','retain_exclusion','confirm_reasoned_exclusion','emissions_overproliferation','This is part of the previously overgrown emissions matrix (gas/sector/LULUCF variants). Even when technically valid, it is too repetitive or specialized relative to a small set of broad emissions anchors.','Keep excluded; any future emissions expansion must demonstrate a genuinely new player-facing concept rather than another gas/sector slice.','',''),
  ('legacy:1893',1893,'Lowest alcohol-attributable death rate','WHO','Health · SA_0000001807_AA','','52','hold_for_family_curation','keep_reaudit_block','specialty_health_density','Potentially valid but narrower/specialized than stronger health anchors or closely related to another retained access/care measure.','Keep quarantined pending health-family curation and coverage review.','family:who:lowest-harmful-alcohol-use','hold_for_individual_editorial_review'),
  ('legacy:1895',1895,'Highest renewable energy consumption','World Bank','Energy · EG.FEC.RNEW\.ZS','','51','advance_to_validation','clear_generic_legacy_block','broad_intuitive_distinct','Renewable-energy consumption share is a broad and understandable energy-system measure, distinct from renewable electricity generation/share.','Resolve the exact current series, validate country coverage and denominator, and keep fail-closed until source-family checks pass.','',''),
  ('legacy:1898',1898,'Highest primary reading proficiency','UNESCO UIS','Education · READ.PRIMARY','verified','50','hold_for_family_curation','keep_reaudit_block','family_density_near_duplicate','Plausible in isolation, but too close to a stronger retained stage/subject/infrastructure anchor or part of an over-dense education family; needs family-level curation before any legacy block is cleared.','Keep quarantined; compare against the selected UNESCO anchors and only promote if it adds a clearly different player experience.','family:unesco:highest-reading-proficiency-primary','ready_for_source_family_validation'),
  ('legacy:1902',1902,'Highest collective-bargaining coverage','ILOSTAT','Labor · ILR_CBCT_NOC_RT_A','verified','48','hold_for_family_curation','keep_reaudit_block','labor_methodology_or_density','Potentially useful, but either jargon/denominator-sensitive, source-repair dependent, a subgroup variant, or a lower-priority specialty labor measure; it needs family-level comparison before activation.','Keep fail-closed while curating the ILOSTAT family; promote only if the definition is intuitive and it adds a distinct board experience.','family:ilostat:highest-collective-bargaining','hold_for_individual_editorial_review'),
  ('legacy:1908',1908,'Highest doctor density','WHO','Healthcare · HWF_0001','','45','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:highest-doctor-density','ready_for_source_family_validation'),
  ('legacy:1909',1909,'Lowest cigarette-smoking rate','WHO','Health · Yth_curr_cig_smoking','','45','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:lowest-cigarette-smoking','ready_for_source_family_validation'),
  ('legacy:1910',1910,'Highest pharmacist density','WHO','Healthcare · HWF_0014','','45','hold_for_family_curation','keep_reaudit_block','specialty_health_density','Potentially valid but narrower/specialized than stronger health anchors or closely related to another retained access/care measure.','Keep quarantined pending health-family curation and coverage review.','family:who:highest-pharmacist-density','ready_for_source_family_validation'),
  ('legacy:1911',1911,'Highest antenatal-care coverage','WHO','Maternal Health · WHS4_154','','45','hold_for_family_curation','keep_reaudit_block','specialty_health_density','Potentially valid but narrower/specialized than stronger health anchors or closely related to another retained access/care measure.','Keep quarantined pending health-family curation and coverage review.','family:who:highest-antenatal-care','ready_for_source_family_validation'),
  ('legacy:1914',1914,'Highest life expectancy','WHO','Health · WHOSIS_000001','','42','advance_to_validation','clear_generic_legacy_block','source_superseded_concept_retained','Life expectancy is a core world-knowledge category; the concept should survive even though the old WHO row was rejected because the current build has a preferred UN WPP source path.','Use UN World Population Prospects 2024 as the preferred source and clear only the historical generic-title veto.','candidate:074','ready_for_validated_import'),
  ('legacy:1917',1917,'Highest handwashing access','WHO','Infrastructure · WSH_HYGIENE_BASIC','','39','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:highest-handwashing-access','ready_for_source_family_validation'),
  ('legacy:1918',1918,'Highest healthy life expectancy','WHO','Health · WHOSIS_000002','','38','retain_exclusion','confirm_reasoned_exclusion','near_duplicate_less_intuitive','Healthy life expectancy is substantially less intuitive to players and too close to the stronger ordinary life-expectancy category for the core catalog.','Keep excluded; retain ordinary life expectancy as the anchor.','family:who:highest-healthy-life-expectancy','ready_for_source_family_validation'),
  ('legacy:1919',1919,'Lowest high-blood-pressure rate','WHO','Health · NCD_HYP_PREVALENCE_A','failed','38','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:lowest-high-blood-pressure-rate','ready_for_source_family_validation'),
  ('legacy:1922',1922,'Highest hospital-bed density','WHO','Healthcare · GDO_q9x1_3','','33','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:highest-hospital-bed-density','ready_for_source_family_validation'),
  ('legacy:1924',1924,'Lowest suicide rate','WHO','Health · MH_12','','25','advance_to_validation','clear_generic_legacy_block','broad_health_anchor','Broad, recognizable public-health or health-system measure that adds a distinct player-facing dimension and is not merely a demographic slice.','Validate the WHO source-family series, denominator, year consistency and coverage; retain fail-closed status until those gates pass.','family:who:lowest-suicide-rate','ready_for_source_family_validation')

on conflict(legacy_key) do update set
  source_line=excluded.source_line,
  category_title=excluded.category_title,
  legacy_source=excluded.legacy_source,
  legacy_domain_series=excluded.legacy_domain_series,
  historical_integrity_status=excluded.historical_integrity_status,
  historical_quality=excluded.historical_quality,
  editorial_disposition=excluded.editorial_disposition,
  legacy_guard_action=excluded.legacy_guard_action,
  reason_class=excluded.reason_class,
  first_principles_rationale=excluded.first_principles_rationale,
  recommended_next_action=excluded.recommended_next_action,
  linked_tracker_ids=excluded.linked_tracker_ids,
  linked_tracker_dispositions=excluded.linked_tracker_dispositions,
  reviewed_at=now();

update public.legacy_category_rejections_v16_2_6 r
set default_decision = case a.legacy_guard_action
      when 'clear_generic_legacy_block' then 'cleared_for_reconsideration'
      when 'confirm_reasoned_exclusion' then 'confirmed_exclusion'
      else 'requires_reaudit'
    end,
    required_action = a.recommended_next_action
from public.legacy_rejection_first_principles_reaudit_v16_2_6 a
where a.legacy_key=r.legacy_key;

update public.legacy_rejection_semantic_aliases_v16_2_6 s
set review_status = case a.legacy_guard_action
      when 'clear_generic_legacy_block' then 'cleared'
      when 'confirm_reasoned_exclusion' then 'confirmed_exclusion'
      else 'requires_reaudit'
    end,
    rationale = concat(s.rationale, ' | Priority-150 first-principles review: ', a.first_principles_rationale)
from public.legacy_rejection_first_principles_reaudit_v16_2_6 a
where a.legacy_key=s.legacy_key;

alter table public.tracker_legacy_rejection_collisions_v16_2_6 add column if not exists reaudit_disposition text;
alter table public.tracker_legacy_rejection_collisions_v16_2_6 add column if not exists reaudit_guard_action text;

update public.tracker_legacy_rejection_collisions_v16_2_6 c
set reaudit_disposition=a.editorial_disposition,
    reaudit_guard_action=a.legacy_guard_action
from public.legacy_rejection_first_principles_reaudit_v16_2_6 a
where a.source_line=c.legacy_source_line;

-- Fail-safe: a "cleared" legacy decision is only removal of the historical veto.
-- The runtime view continues to require editorial approval, strict quality pass,
-- no hard source/integrity blocker, and no remaining legacy blocker.
commit;
