begin;
select pg_advisory_xact_lock(hashtext('geostats-v16.3.4-runtime-catalog'));
create temporary table suitability_review on commit drop as select * from jsonb_to_recordset($review$[{"id": "unhcr:most-stateless-people", "status": "rejected", "reason": "Owner-approved source suitability removal: incomplete country reporting cannot support an unrestricted stateless-population ranking."}, {"id": "natural-earth:largest-mapped-glaciated-area", "status": "rejected", "reason": "Owner-approved source suitability removal: Natural Earth glaciated areas include outdated glacier extents."}, {"id": "natural-earth:highest-mapped-glaciated-share", "status": "rejected", "reason": "Owner-approved source suitability removal: Natural Earth glaciated areas include outdated glacier extents."}, {"id": "natural-earth:highest-mapped-river-density", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:most-mapped-river-length", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:most-mapped-rivers", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:most-mapped-lakes", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:largest-mapped-lake-area", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:highest-mapped-lake-share", "status": "rejected", "reason": "Owner-approved source suitability removal: selective cartographic river/lake coverage is unsuitable for comprehensive country counts, totals or density rankings."}, {"id": "natural-earth:longest-coastline", "status": "needs_data_repair", "reason": "Paused by owner-approved source suitability review: generalized coastline rankings require stronger cross-source validation."}, {"id": "natural-earth:highest-coastline-density", "status": "needs_data_repair", "reason": "Paused by owner-approved source suitability review: generalized coastline rankings require stronger cross-source validation."}]$review$::jsonb) x(id text,status text,reason text);
create temporary table suitability_before on commit drop as select id,enabled from public.stat_categories;
insert into public.category_review_contracts_v16_3_4 as c(category_id,review_patch,presentation_patch)
select id,jsonb_build_object('status',status,'notes',reason),'{}'::jsonb from suitability_review
on conflict(category_id) do update set review_patch=c.review_patch||excluded.review_patch,revision=c.revision+1,updated_at=now();
update public.category_review_state r set status=s.status,notes=s.reason,updated_at=now() from suitability_review s where r.category_id=s.id;
update public.stat_categories c set enabled=false,eligible_daily=false,review_status=case when s.status='needs_data_repair' then 'needs_review' else s.status end,curation_status='excluded',content_review_status='excluded',player_quality_status='blocked' from suitability_review s where c.id=s.id;
do $$ begin
 if (select count(*) from public.stat_categories where enabled)<>354 then raise exception 'Unexpected catalog size after source suitability review'; end if;
 if exists(select 1 from public.category_runtime_review_v16_2 r join suitability_review s using(id) where r.enabled or r.computed_playable_v16_2) then raise exception 'Unsuitable source still playable'; end if;
 if exists(select 1 from suitability_before b join public.stat_categories c using(id) where b.enabled is distinct from c.enabled and not exists(select 1 from suitability_review s where s.id=c.id)) then raise exception 'Unrequested membership change'; end if;
end $$;
commit;
