"""Canonical player-facing names for GeoStats' 195-country universe."""

CANONICAL_COUNTRY_NAMES: dict[str, str] = {
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'AND': 'Andorra',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua and Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHR': 'Bahrain',
    'BHS': 'The Bahamas',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRN': 'Brunei',
    'BTN': 'Bhutan',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': 'Côte d’Ivoire',
    'CMR': 'Cameroon',
    'COD': 'Democratic Republic of the Congo',
    'COG': 'Republic of the Congo',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cabo Verde',
    'CRI': 'Costa Rica',
    'CUB': 'Cuba',
    'CYP': 'Cyprus',
    'CZE': 'Czechia',
    'DEU': 'Germany',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIN': 'Finland',
    'FJI': 'Fiji',
    'FRA': 'France',
    'FSM': 'Micronesia',
    'GAB': 'Gabon',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'The Gambia',
    'GNB': 'Guinea-Bissau',
    'GNQ': 'Equatorial Guinea',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HTI': 'Haiti',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Ireland',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KNA': 'Saint Kitts and Nevis',
    'KOR': 'South Korea',
    'KWT': 'Kuwait',
    'LAO': 'Laos',
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LCA': 'Saint Lucia',
    'LIE': 'Liechtenstein',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAR': 'Morocco',
    'MCO': 'Monaco',
    'MDA': 'Moldova',
    'MDG': 'Madagascar',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MHL': 'Marshall Islands',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'NAM': 'Namibia',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NPL': 'Nepal',
    'NRU': 'Nauru',
    'NZL': 'New Zealand',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PLW': 'Palau',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRK': 'North Korea',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'Palestine',
    'QAT': 'Qatar',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SGP': 'Singapore',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOM': 'Somalia',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'STP': 'São Tomé and Príncipe',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'SYC': 'Seychelles',
    'SYR': 'Syria',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Türkiye',
    'TUV': 'Tuvalu',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URY': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VAT': 'Vatican City',
    'VCT': 'Saint Vincent and the Grenadines',
    'VEN': 'Venezuela',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'YEM': 'Yemen',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe',
}

ISO2_TO_ISO3: dict[str, str] = {
    'AD': 'AND',
    'AE': 'ARE',
    'AF': 'AFG',
    'AG': 'ATG',
    'AL': 'ALB',
    'AM': 'ARM',
    'AO': 'AGO',
    'AR': 'ARG',
    'AT': 'AUT',
    'AU': 'AUS',
    'AZ': 'AZE',
    'BA': 'BIH',
    'BB': 'BRB',
    'BD': 'BGD',
    'BE': 'BEL',
    'BF': 'BFA',
    'BG': 'BGR',
    'BH': 'BHR',
    'BI': 'BDI',
    'BJ': 'BEN',
    'BN': 'BRN',
    'BO': 'BOL',
    'BR': 'BRA',
    'BS': 'BHS',
    'BT': 'BTN',
    'BW': 'BWA',
    'BY': 'BLR',
    'BZ': 'BLZ',
    'CA': 'CAN',
    'CD': 'COD',
    'CF': 'CAF',
    'CG': 'COG',
    'CH': 'CHE',
    'CI': 'CIV',
    'CL': 'CHL',
    'CM': 'CMR',
    'CN': 'CHN',
    'CO': 'COL',
    'CR': 'CRI',
    'CU': 'CUB',
    'CV': 'CPV',
    'CY': 'CYP',
    'CZ': 'CZE',
    'DE': 'DEU',
    'DJ': 'DJI',
    'DK': 'DNK',
    'DM': 'DMA',
    'DO': 'DOM',
    'DZ': 'DZA',
    'EC': 'ECU',
    'EE': 'EST',
    'EG': 'EGY',
    'ER': 'ERI',
    'ES': 'ESP',
    'ET': 'ETH',
    'FI': 'FIN',
    'FJ': 'FJI',
    'FM': 'FSM',
    'FR': 'FRA',
    'GA': 'GAB',
    'GB': 'GBR',
    'GD': 'GRD',
    'GE': 'GEO',
    'GH': 'GHA',
    'GM': 'GMB',
    'GN': 'GIN',
    'GQ': 'GNQ',
    'GR': 'GRC',
    'GT': 'GTM',
    'GW': 'GNB',
    'GY': 'GUY',
    'HN': 'HND',
    'HR': 'HRV',
    'HT': 'HTI',
    'HU': 'HUN',
    'ID': 'IDN',
    'IE': 'IRL',
    'IL': 'ISR',
    'IN': 'IND',
    'IQ': 'IRQ',
    'IR': 'IRN',
    'IS': 'ISL',
    'IT': 'ITA',
    'JM': 'JAM',
    'JO': 'JOR',
    'JP': 'JPN',
    'KE': 'KEN',
    'KG': 'KGZ',
    'KH': 'KHM',
    'KI': 'KIR',
    'KM': 'COM',
    'KN': 'KNA',
    'KP': 'PRK',
    'KR': 'KOR',
    'KW': 'KWT',
    'KZ': 'KAZ',
    'LA': 'LAO',
    'LB': 'LBN',
    'LC': 'LCA',
    'LI': 'LIE',
    'LK': 'LKA',
    'LR': 'LBR',
    'LS': 'LSO',
    'LT': 'LTU',
    'LU': 'LUX',
    'LV': 'LVA',
    'LY': 'LBY',
    'MA': 'MAR',
    'MC': 'MCO',
    'MD': 'MDA',
    'ME': 'MNE',
    'MG': 'MDG',
    'MH': 'MHL',
    'MK': 'MKD',
    'ML': 'MLI',
    'MM': 'MMR',
    'MN': 'MNG',
    'MR': 'MRT',
    'MT': 'MLT',
    'MU': 'MUS',
    'MV': 'MDV',
    'MW': 'MWI',
    'MX': 'MEX',
    'MY': 'MYS',
    'MZ': 'MOZ',
    'NA': 'NAM',
    'NE': 'NER',
    'NG': 'NGA',
    'NI': 'NIC',
    'NL': 'NLD',
    'NO': 'NOR',
    'NP': 'NPL',
    'NR': 'NRU',
    'NZ': 'NZL',
    'OM': 'OMN',
    'PA': 'PAN',
    'PE': 'PER',
    'PG': 'PNG',
    'PH': 'PHL',
    'PK': 'PAK',
    'PL': 'POL',
    'PS': 'PSE',
    'PT': 'PRT',
    'PW': 'PLW',
    'PY': 'PRY',
    'QA': 'QAT',
    'RO': 'ROU',
    'RS': 'SRB',
    'RU': 'RUS',
    'RW': 'RWA',
    'SA': 'SAU',
    'SB': 'SLB',
    'SC': 'SYC',
    'SD': 'SDN',
    'SE': 'SWE',
    'SG': 'SGP',
    'SI': 'SVN',
    'SK': 'SVK',
    'SL': 'SLE',
    'SM': 'SMR',
    'SN': 'SEN',
    'SO': 'SOM',
    'SR': 'SUR',
    'SS': 'SSD',
    'ST': 'STP',
    'SV': 'SLV',
    'SY': 'SYR',
    'SZ': 'SWZ',
    'TD': 'TCD',
    'TG': 'TGO',
    'TH': 'THA',
    'TJ': 'TJK',
    'TL': 'TLS',
    'TM': 'TKM',
    'TN': 'TUN',
    'TO': 'TON',
    'TR': 'TUR',
    'TT': 'TTO',
    'TV': 'TUV',
    'TZ': 'TZA',
    'UA': 'UKR',
    'UG': 'UGA',
    'US': 'USA',
    'UY': 'URY',
    'UZ': 'UZB',
    'VA': 'VAT',
    'VC': 'VCT',
    'VE': 'VEN',
    'VN': 'VNM',
    'VU': 'VUT',
    'WS': 'WSM',
    'YE': 'YEM',
    'ZA': 'ZAF',
    'ZM': 'ZMB',
    'ZW': 'ZWE',
}


def canonical_country_name(iso3: str, fallback: str | None = None) -> str:
    """Return the fixed GeoStats display name; source labels are never player-facing."""
    return CANONICAL_COUNTRY_NAMES.get(iso3, fallback or iso3)


def country_alpha2_to_iso3(value: object) -> str | None:
    """Map an ISO 3166-1 alpha-2 code into GeoStats' 195-state ISO3 universe."""
    code = str(value or "").strip().upper()
    return ISO2_TO_ISO3.get(code)


def _normalized_country_key(value: str) -> str:
    import unicodedata
    normalized = unicodedata.normalize("NFKD", value or "")
    normalized = "".join(char for char in normalized if not unicodedata.combining(char))
    normalized = normalized.lower().replace("&", " and ")
    return " ".join("".join(char if char.isalnum() else " " for char in normalized).split())


_COUNTRY_NAME_TO_ISO3 = {
    _normalized_country_key(name): iso3
    for iso3, name in CANONICAL_COUNTRY_NAMES.items()
}
_COUNTRY_NAME_TO_ISO3.update({
    "bahamas": "BHS",
    "the bahamas": "BHS",
    "bahamas the": "BHS",
    "gambia": "GMB",
    "the gambia": "GMB",
    "bolivia plurinational state of": "BOL",
    "bolivia": "BOL",
    "brunei darussalam": "BRN",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "congo": "COG",
    "congo republic of the": "COG",
    "democratic republic of the congo": "COD",
    "congo democratic republic of the": "COD",
    "cote d ivoire": "CIV",
    "ivory coast": "CIV",
    "czech republic": "CZE",
    "eswatini": "SWZ",
    "swaziland": "SWZ",
    "holy see": "VAT",
    "vatican": "VAT",
    "iran islamic republic of": "IRN",
    "korea democratic people s republic of": "PRK",
    "democratic people s republic of korea": "PRK",
    "north korea": "PRK",
    "korea republic of": "KOR",
    "republic of korea": "KOR",
    "south korea": "KOR",
    "lao people s democratic republic": "LAO",
    "laos": "LAO",
    "micronesia federated states of": "FSM",
    "moldova republic of": "MDA",
    "republic of moldova": "MDA",
    "palestinian territories": "PSE",
    "state of palestine": "PSE",
    "palestine state of": "PSE",
    "russian federation": "RUS",
    "sao tome and principe": "STP",
    "syrian arab republic": "SYR",
    "taiwan": "",
    "tanzania united republic of": "TZA",
    "timor leste": "TLS",
    "turkey": "TUR",
    "turkiye": "TUR",
    "united republic of tanzania": "TZA",
    "united states of america": "USA",
    "venezuela bolivarian republic of": "VEN",
    "viet nam": "VNM",
    # Current United Nations Member States page labels.
    "china the people s republic of": "CHN",
    "china people s republic of": "CHN",
    "gambia republic of the": "GMB",
    "guinea bissau": "GNB",
    "naoero": "NRU",
    "netherlands kingdom of the": "NLD",
    "united kingdom of great britain and northern ireland": "GBR",
})


def country_name_to_iso3(value: object) -> str | None:
    """Map common official-source country labels into GeoStats' 195-state universe."""
    key = _normalized_country_key(str(value or ""))
    code = _COUNTRY_NAME_TO_ISO3.get(key)
    return code or None
