"""Complete editorial curation rules for GeoStats v13.4.3."""
CURATION_VERSION = 'geostats-v13.4.3-complete-catalog-v1'
FAOSTAT_ALLOWED = {
    "QCL:'0111:5510": 'Most wheat produced',
    "QCL:'0112:5510": 'Most corn produced',
    "QCL:'0113:5510": 'Most rice produced',
    "QCL:'0114:5510": 'Most sorghum produced',
    "QCL:'0115:5510": 'Most barley produced',
    "QCL:'0117:5510": 'Most oats produced',
    "QCL:'0118:5510": 'Most millet produced',
    "QCL:'01212:5510": 'Most cabbage produced',
    "QCL:'01213:5510": 'Most cauliflower and broccoli produced',
    "QCL:'01214:5510": 'Most lettuce and chicory produced',
    "QCL:'01221:5510": 'Most watermelons produced',
    "QCL:'01229:5510": 'Most melons produced',
    "QCL:'01231:5510": 'Most green chilies and peppers produced',
    "QCL:'01232:5510": 'Most cucumbers and gherkins produced',
    "QCL:'01233:5510": 'Most eggplants produced',
    "QCL:'01234:5510": 'Most tomatoes produced',
    "QCL:'01235:5510": 'Most pumpkins, squash, and gourds produced',
    "QCL:'01242:5510": 'Most green peas produced',
    "QCL:'01251:5510": 'Most carrots and turnips produced',
    "QCL:'01253.02:5510": 'Most onions and shallots produced',
    "QCL:'01270:5510": 'Most mushrooms and truffles produced',
    "QCL:'01311:5510": 'Most avocado produced',
    "QCL:'01312:5510": 'Most bananas produced',
    "QCL:'01315:5510": 'Most figs produced',
    "QCL:'01316:5510": 'Most mangoes, guavas, and mangosteens produced',
    "QCL:'01317:5510": 'Most papaya produced',
    "QCL:'01318:5510": 'Most pineapple produced',
    "QCL:'01321:5510": 'Most grapefruits and pomelos produced',
    "QCL:'01322:5510": 'Most lemons and limes produced',
    "QCL:'01323:5510": 'Most oranges produced',
    "QCL:'01324:5510": 'Most mandarins and tangerines produced',
    "QCL:'01330:5510": 'Most grapes produced',
    "QCL:'01341:5510": 'Most apples produced',
    "QCL:'01342.01:5510": 'Most pears produced',
    "QCL:'01343:5510": 'Most apricot produced',
    "QCL:'01344.02:5510": 'Most cherries produced',
    "QCL:'01345:5510": 'Most peaches and nectarines produced',
    "QCL:'01346:5510": 'Most plums and sloes produced',
    "QCL:'01354:5510": 'Most strawberries produced',
    "QCL:'01371:5510": 'Most almonds produced',
    "QCL:'01376:5510": 'Most walnuts produced',
    "QCL:'0141:5510": 'Most soybeans produced',
    "QCL:'0142:5510": 'Most peanuts produced',
    "QCL:'01444:5510": 'Most sesame seeds produced',
    "QCL:'01445:5510": 'Most sunflower seeds produced',
    "QCL:'01460:5510": 'Most coconuts produced',
    "QCL:'01510:5510": 'Most potatoes produced',
    "QCL:'01520.01:5510": 'Most cassava produced',
    "QCL:'01530:5510": 'Most sweet potatoes produced',
    "QCL:'01610:5510": 'Most coffee produced',
    "QCL:'01701:5510": 'Most dry beans produced',
    "QCL:'01705:5510": 'Most dry peas produced',
    "QCL:'01801:5510": 'Most sugar beets produced',
    "QCL:'01802:5510": 'Most sugarcane produced',
    "QCL:'01921.02:5510": 'Most cotton produced',
    "QCL:'01970:5510": 'Most tobacco produced',
    "QCL:'02211:5510": "Most cow's milk produced",
    "QCL:'02292:5510": 'Most goat milk produced',
    "QCL:'0231:5513": 'Most eggs produced',
    "QCL:'02910:5510": 'Most honey produced',
    "QCL:'21113.01:5510": 'Most pork produced',
    "QCL:'21121:5510": 'Most chicken meat produced',
    "QCL:'2351f:5510": 'Most cane and beet sugar produced',
    "QCL:'24212.02:5510": 'Most wine produced',
    "QCL:'24310.01:5510": 'Most beer produced',
    "QCL:'F1717:5510": 'Most cereals produced',
    "QCL:'F1720:5510": 'Most roots and tubers produced',
    "QCL:'F1726:5510": 'Most pulses, total produced',
    "QCL:'F1729:5510": 'Most tree nuts produced',
    "QCL:'F1735:5510": 'Most vegetables produced',
    "QCL:'F1738:5510": 'Most fruit produced',
    "QCL:'F1745:5510": 'Most cheese produced',
    "QCL:'F1806:5510": 'Most beef and buffalo meat produced',
    "QCL:'F1807:5510": 'Most sheep and goat meat produced',
    "QCL:'F1811:5510": 'Most butter and ghee produced',
}
EXCLUDED_SOURCE_CODES = {
    'World Bank': {
        'AG.LND.AGRI.K2': 'Near-duplicate of land area and arable-land totals.',
        'AG.LND.AGRI.ZS': 'Near-duplicate of arable-land share.',
        'NE.CON.GOVT.CD': 'Absolute consumption mostly repeats economy size and is weak for gameplay.',
        'NE.CON.PRVT.CD': 'Absolute consumption mostly repeats economy size and is weak for gameplay.',
        'NE.EXP.GNFS.CD': 'Superseded by the broader-coverage merchandise-exports category.',
        'NE.IMP.GNFS.CD': 'Superseded by the broader-coverage merchandise-imports category.',
        'NV.SRV.TOTL.ZS': 'Complementary near-duplicate of industry share of GDP.',
        'SP.RUR.TOTL': 'Near-duplicate of total population and rural population share.',
        'SP.URB.TOTL': 'Near-duplicate of total population and urbanization measures.',
    },
    'UNHCR': {
        'population:coa:asylum_seekers': 'Stock measure is too similar to refugees hosted and asylum applications received.',
        'population:coo:asylum_seekers': 'Stock measure is too similar to refugees originating and asylum-application flows.',
    },
    'UNESCO UIS': {
        'CR.MOD.2': 'Middle-stage completion is redundant when primary and upper-secondary completion are retained.',
        'GER.1': 'Gross enrollment can exceed 100 percent and is less intuitive than completion rates.',
        'ROFST.MOD.2': 'Near-inverse of lower-secondary completion and too similar to other school-attainment categories.',
        'ROFST.MOD.3': 'Near-inverse of upper-secondary completion and too similar to other school-attainment categories.',
    },
    'Natural Earth': {
        'largest-geographic-span': 'Ambiguous diagonal extent; north-south span is clearer and retained.',
    },
}


# Complete v13.4.3 additions reviewed from the 273-row fail-closed export.
ADDITIONAL_APPROVED_SOURCE_CODES = {'ILOSTAT': {'SDG_0111_SEX_AGE_RT_A': 'Lowest working-poverty rate', 'EIP_NEET_SEX_RT_A': 'Lowest youth NEET rate', 'EMP_NIFL_SEX_RT_A': 'Lowest informal-employment rate', 'SDG_0552_NOC_RT_A': 'Highest share of women in management', 'HOW_UEES_SEX_NB_A': 'Longest average working week', 'UNE_3EAP_SEX_AGE_DSB_RT_A': 'Lowest youth unemployment rate'}, 'Natural Earth': {'most-land-neighbors': 'Most bordering countries'}, 'U.S. EIA': {'57:1': 'Most crude oil produced', '26:1': 'Most natural gas produced'}, 'UN Comtrade': {'0803': 'Largest banana exports', '7108': 'Largest gold exports', '0902': 'Largest tea exports', '1801': 'Largest cocoa-bean exports', '2709': 'Largest crude-oil exports', '1001': 'Largest wheat exports'}, 'UNESCO UIS': {'XGDP.FSGOV': 'Highest education spending share of GDP', 'GTVP.2T3.V': 'Highest vocational enrollment share', '26637': 'Most international students hosted', 'MOR.5T8.40505': 'Highest outbound student mobility', 'SCHBSP.1.WCOMPUT': 'Highest school computer access', 'FOSGP.5T8.F500600700': 'Highest STEM graduate share', 'SCHBSP.1.WINTERN': 'Highest school internet access', 'SCHBSP.1.WELEC': 'Highest school electricity access', 'RESDEN.INHAB.TFTE': 'Most researchers per million people', 'READ.LOWERSEC': 'Highest lower-secondary reading proficiency', 'SCHBSP.1.WTOILA': 'Highest school sanitation access', 'SCHBSP.1.WWATA': 'Highest school drinking-water access', 'LR.AG15T24': 'Highest youth literacy rate', 'MATH.LOWERSEC': 'Highest lower-secondary mathematics proficiency'}, 'UNHCR': {'population:coa:stateless': 'Most stateless people', 'solutions:coo:returned_refugees': 'Most refugees returned home', 'population:coa:idps': 'Most internally displaced people'}, 'WHO': {'WSH_WATER_SAFELY_MANAGED': 'Highest safely managed drinking-water access', 'WSH_SANITATION_SAFELY_MANAGED': 'Highest safely managed sanitation access', 'HWF_0006': 'Highest nurse and midwife density', 'HWF_0001': 'Highest doctor density', 'NCD_HYP_PREVALENCE_A': 'Lowest high-blood-pressure rate', 'MALARIA_EST_INCIDENCE': 'Lowest malaria incidence', 'RS_198': 'Lowest road-traffic death rate', 'MDG_0000000025': 'Highest skilled birth-attendance rate', 'WSH_HYGIENE_BASIC': 'Highest handwashing access', 'WHS4_154': 'Highest antenatal-care coverage'}, 'World Bank': {'EN.GHG.CH4.MT.CE.AR5': 'Highest methane emissions', 'EN.GHG.CO2.MT.CE.AR5': 'Highest total CO₂ emissions', 'EN.GHG.CO2.PC.CE.AR5': 'Highest CO₂ emissions per person', 'IS.AIR.GOOD.MT.K1': 'Most air freight', 'AG.LND.PRCP.MM#rain': 'Highest average rainfall'}}
COMPLETE_REVIEWED_CATEGORY_COUNT = 726
COMPLETE_APPROVED_RULE_COUNT = 252
COMPLETE_EXCLUDED_RULE_COUNT = 474
